// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MiniLoginRequestPlatform.
const (
	MiniLoginRequestPlatformAlipay MiniLoginRequestPlatform = "alipay"
	MiniLoginRequestPlatformWeapp  MiniLoginRequestPlatform = "weapp"
)

// Defines values for MiniLoginRequestRole.
const (
	CS          MiniLoginRequestRole = "CS"
	CUSTOMER    MiniLoginRequestRole = "CUSTOMER"
	PROCUREMENT MiniLoginRequestRole = "PROCUREMENT"
	SALES       MiniLoginRequestRole = "SALES"
)

// Defines values for PasswordLoginRequestRole.
const (
	ADMIN PasswordLoginRequestRole = "ADMIN"
)

// Defines values for SalesQrCodePlatform.
const (
	SalesQrCodePlatformAlipay SalesQrCodePlatform = "alipay"
	SalesQrCodePlatformWeapp  SalesQrCodePlatform = "weapp"
)

// Defines values for UserUserType.
const (
	Admin    UserUserType = "admin"
	Customer UserUserType = "customer"
	Staff    UserUserType = "staff"
)

// Defines values for UserStatus.
const (
	Active   UserStatus = "active"
	Disabled UserStatus = "disabled"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	ExpiresIn   int    `json:"expiresIn"`
	User        User   `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code string `json:"code"`

	// Details Optional metadata (e.g. { "availableRoles": ["CUSTOMER", "SALES"] }).
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"requestId"`
}

// MiniLoginRequest defines model for MiniLoginRequest.
type MiniLoginRequest struct {
	// BindingToken Optional: staff binding token for first-time login
	BindingToken *string `json:"bindingToken,omitempty"`
	Code         string  `json:"code"`

	// PhoneProof Phone authorization proof from mini program platform APIs.
	PhoneProof *PhoneProof              `json:"phoneProof,omitempty"`
	Platform   MiniLoginRequestPlatform `json:"platform"`

	// Role Optional current role; required when multiple roles. ADMIN is not allowed.
	Role *MiniLoginRequestRole `json:"role,omitempty"`

	// Scene Optional: QR scene parameter for sales binding (only applied on first bind)
	Scene *string `json:"scene,omitempty"`
}

// MiniLoginRequestPlatform defines model for MiniLoginRequest.Platform.
type MiniLoginRequestPlatform string

// MiniLoginRequestRole Optional current role; required when multiple roles. ADMIN is not allowed.
type MiniLoginRequestRole string

// PasswordLoginRequest defines model for PasswordLoginRequest.
type PasswordLoginRequest struct {
	Password string `json:"password"`

	// Role Optional; must be ADMIN when provided.
	Role     *PasswordLoginRequestRole `json:"role,omitempty"`
	Username string                    `json:"username"`
}

// PasswordLoginRequestRole Optional; must be ADMIN when provided.
type PasswordLoginRequestRole string

// PhoneProof Phone authorization proof from mini program platform APIs.
type PhoneProof struct {
	// Charset Charset metadata for Alipay phone response.
	Charset *string `json:"charset,omitempty"`

	// Code Platform-issued one-time code used by backend to resolve phone number.
	Code *string `json:"code,omitempty"`

	// EncryptType Encryption algorithm for Alipay phone response (typically AES).
	EncryptType *string `json:"encryptType,omitempty"`

	// Phone Optional direct phone fallback for environments where code exchange is unavailable.
	Phone *string `json:"phone,omitempty"`

	// Response Alipay encrypted response payload returned by my.getPhoneNumber.
	Response *string `json:"response,omitempty"`

	// Sign Signature corresponding to Alipay phone response.
	Sign *string `json:"sign,omitempty"`

	// SignType Signature algorithm for Alipay phone response (typically RSA2).
	SignType *string `json:"signType,omitempty"`
}

// SalesQrCode defines model for SalesQrCode.
type SalesQrCode struct {
	ExpiresAt *time.Time           `json:"expiresAt"`
	Platform  *SalesQrCodePlatform `json:"platform,omitempty"`
	QrCodeUrl string               `json:"qrCodeUrl"`

	// Scene Scene parameter used for sales binding
	Scene string `json:"scene"`
}

// SalesQrCodePlatform defines model for SalesQrCode.Platform.
type SalesQrCodePlatform string

// User defines model for User.
type User struct {
	CreatedAt             time.Time           `json:"createdAt"`
	DisabledAt            *time.Time          `json:"disabledAt"`
	DisabledReason        *string             `json:"disabledReason"`
	DisplayName           *string             `json:"displayName,omitempty"`
	Id                    openapi_types.UUID  `json:"id"`
	OwnerSalesDisplayName *string             `json:"ownerSalesDisplayName"`
	OwnerSalesUserId      *openapi_types.UUID `json:"ownerSalesUserId"`
	Phone                 *string             `json:"phone"`
	Roles                 []string            `json:"roles"`
	Status                *UserStatus         `json:"status,omitempty"`
	UserType              UserUserType        `json:"userType"`
}

// UserUserType defines model for User.UserType.
type UserUserType string

// UserStatus defines model for UserStatus.
type UserStatus string
