run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - unconvert
    - gocritic
    - prealloc
    - bodyclose
    - nilerr
    - gosec

issues:
  exclude-use-default: false
