version: "2"
run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - nilerr
    - prealloc
    - unconvert
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
