packages:
  - apps/*
  - packages/*
  - tools/*

patchedDependencies:
  '@tarojs/components-rn@4.1.9': patches/@tarojs__components-rn@4.1.9.patch
  '@tarojs/vite-runner@4.1.9': patches/@tarojs__vite-runner@4.1.9.patch
