// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearUserDefaultAddresses = `-- name: ClearUserDefaultAddresses :exec
UPDATE user_addresses
SET is_default = false,
    updated_at = now()
WHERE user_id = $1
  AND is_default = true
`

func (q *Queries) ClearUserDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserDefaultAddresses, userID)
	return err
}

const countUserAddresses = `-- name: CountUserAddresses :one
SELECT count(*)
FROM user_addresses
WHERE user_id = $1
`

func (q *Queries) CountUserAddresses(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAddresses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAddress = `-- name: CreateUserAddress :one
INSERT INTO user_addresses (
    user_id,
    receiver_name,
    receiver_phone,
    detail,
    is_default
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
`

type CreateUserAddressParams struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	ReceiverName  string    `db:"receiver_name" json:"receiver_name"`
	ReceiverPhone string    `db:"receiver_phone" json:"receiver_phone"`
	Detail        string    `db:"detail" json:"detail"`
	IsDefault     bool      `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createUserAddress,
		arg.UserID,
		arg.ReceiverName,
		arg.ReceiverPhone,
		arg.Detail,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhone,
		&i.Detail,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserAddress = `-- name: DeleteUserAddress :one
DELETE FROM user_addresses
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
`

type DeleteUserAddressParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, deleteUserAddress, arg.ID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhone,
		&i.Detail,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestUserAddress = `-- name: GetLatestUserAddress :one
SELECT id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
FROM user_addresses
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUserAddress(ctx context.Context, userID uuid.UUID) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getLatestUserAddress, userID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhone,
		&i.Detail,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAddress = `-- name: GetUserAddress :one
SELECT id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
FROM user_addresses
WHERE id = $1
  AND user_id = $2
`

type GetUserAddressParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserAddress(ctx context.Context, arg GetUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getUserAddress, arg.ID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhone,
		&i.Detail,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAddresses = `-- name: ListUserAddresses :many
SELECT id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
FROM user_addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListUserAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, listUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReceiverName,
			&i.ReceiverPhone,
			&i.Detail,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAddressDefault = `-- name: SetUserAddressDefault :one
UPDATE user_addresses
SET is_default = $3,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
`

type SetUserAddressDefaultParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	IsDefault bool      `db:"is_default" json:"is_default"`
}

func (q *Queries) SetUserAddressDefault(ctx context.Context, arg SetUserAddressDefaultParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, setUserAddressDefault, arg.ID, arg.UserID, arg.IsDefault)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhone,
		&i.Detail,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE user_addresses
SET receiver_name = COALESCE($1, receiver_name),
    receiver_phone = COALESCE($2, receiver_phone),
    detail = COALESCE($3, detail),
    is_default = COALESCE($4, is_default),
    updated_at = now()
WHERE id = $5
  AND user_id = $6
RETURNING id, user_id, receiver_name, receiver_phone, detail, is_default, created_at, updated_at
`

type UpdateUserAddressParams struct {
	ReceiverName  *string   `db:"receiver_name" json:"receiver_name"`
	ReceiverPhone *string   `db:"receiver_phone" json:"receiver_phone"`
	Detail        *string   `db:"detail" json:"detail"`
	IsDefault     *bool     `db:"is_default" json:"is_default"`
	ID            uuid.UUID `db:"id" json:"id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, updateUserAddress,
		arg.ReceiverName,
		arg.ReceiverPhone,
		arg.Detail,
		arg.IsDefault,
		arg.ID,
		arg.UserID,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReceiverName,
		&i.ReceiverPhone,
		&i.Detail,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
