// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_catalog_review.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminCatalogProducts = `-- name: CountAdminCatalogProducts :one
SELECT count(*)
FROM catalog_products p
WHERE ($1::text IS NULL OR
    position(lower(btrim($1::text)) in lower(p.name || ' ' || p.id::text)) > 0 OR
    EXISTS (SELECT 1 FROM catalog_skus s WHERE s.product_id = p.id AND
      position(lower(btrim($1::text)) in lower(s.name || ' ' || coalesce(s.sku_code, ''))) > 0) OR
    EXISTS (SELECT 1 FROM catalog_categories c WHERE c.id = p.category_id AND
      position(lower(btrim($1::text)) in lower(c.name)) > 0))
  AND ($2::uuid IS NULL OR p.category_id = $2)
  AND ($3::text IS NULL OR p.status = $3)
  AND (NOT $4::boolean OR EXISTS (
      SELECT 1 FROM product_import_reviews r WHERE r.product_id = p.id AND r.status = 'PENDING'
  ))
`

type CountAdminCatalogProductsParams struct {
	Q           *string     `db:"q" json:"q"`
	CategoryID  pgtype.UUID `db:"category_id" json:"category_id"`
	Status      *string     `db:"status" json:"status"`
	NeedsReview bool        `db:"needs_review" json:"needs_review"`
}

func (q *Queries) CountAdminCatalogProducts(ctx context.Context, arg CountAdminCatalogProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminCatalogProducts,
		arg.Q,
		arg.CategoryID,
		arg.Status,
		arg.NeedsReview,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProductImportSourceEvidence = `-- name: ListProductImportSourceEvidence :many
SELECT refs.product_id, refs.sku_id, refs.source_namespace, refs.source_product_key, refs.source_sku_key,
       coalesce(rows.row_data, '{}'::jsonb)::jsonb AS source_data
FROM product_import_source_refs refs
LEFT JOIN LATERAL (
    SELECT r.row_data FROM product_import_rows r
    WHERE r.job_id = refs.last_job_id AND r.product_id = refs.product_id
      AND r.sku_id IS NOT DISTINCT FROM refs.sku_id
    ORDER BY r.line_no LIMIT 1
) rows ON true
WHERE refs.product_id = ANY($1::uuid[])
ORDER BY refs.product_id, refs.source_namespace, refs.source_product_key, refs.source_sku_key
`

type ListProductImportSourceEvidenceRow struct {
	ProductID        uuid.UUID       `db:"product_id" json:"product_id"`
	SkuID            pgtype.UUID     `db:"sku_id" json:"sku_id"`
	SourceNamespace  string          `db:"source_namespace" json:"source_namespace"`
	SourceProductKey string          `db:"source_product_key" json:"source_product_key"`
	SourceSkuKey     string          `db:"source_sku_key" json:"source_sku_key"`
	SourceData       json.RawMessage `db:"source_data" json:"source_data"`
}

func (q *Queries) ListProductImportSourceEvidence(ctx context.Context, productIds []uuid.UUID) ([]ListProductImportSourceEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listProductImportSourceEvidence, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductImportSourceEvidenceRow
	for rows.Next() {
		var i ListProductImportSourceEvidenceRow
		if err := rows.Scan(
			&i.ProductID,
			&i.SkuID,
			&i.SourceNamespace,
			&i.SourceProductKey,
			&i.SourceSkuKey,
			&i.SourceData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productActiveWithPendingReview = `-- name: ProductActiveWithPendingReview :one
SELECT EXISTS (
    SELECT 1 FROM catalog_products p JOIN product_import_reviews r ON r.product_id = p.id
    WHERE p.id = $1 AND p.status = 'ACTIVE' AND r.status = 'PENDING'
)
`

func (q *Queries) ProductActiveWithPendingReview(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, productActiveWithPendingReview, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
