// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart_import.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCartImportJob = `-- name: CreateCartImportJob :one
INSERT INTO cart_import_jobs (
    owner_user_id,
    status,
    progress,
    auto_added_count,
    pending_count
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, owner_user_id, status, progress, auto_added_count, pending_count, created_at, updated_at
`

type CreateCartImportJobParams struct {
	OwnerUserID    uuid.UUID `db:"owner_user_id" json:"owner_user_id"`
	Status         string    `db:"status" json:"status"`
	Progress       int32     `db:"progress" json:"progress"`
	AutoAddedCount int32     `db:"auto_added_count" json:"auto_added_count"`
	PendingCount   int32     `db:"pending_count" json:"pending_count"`
}

func (q *Queries) CreateCartImportJob(ctx context.Context, arg CreateCartImportJobParams) (CartImportJob, error) {
	row := q.db.QueryRow(ctx, createCartImportJob,
		arg.OwnerUserID,
		arg.Status,
		arg.Progress,
		arg.AutoAddedCount,
		arg.PendingCount,
	)
	var i CartImportJob
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Status,
		&i.Progress,
		&i.AutoAddedCount,
		&i.PendingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCartImportRow = `-- name: CreateCartImportRow :one
INSERT INTO cart_import_rows (
    job_id,
    row_no,
    raw_name,
    raw_spec,
    raw_qty,
    match_type,
    sku_id,
    qty,
    candidate_sku_ids,
    selected_sku_id,
    selected_qty
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, job_id, row_no, raw_name, raw_spec, raw_qty, match_type, sku_id, qty, candidate_sku_ids, selected_sku_id, selected_qty, created_at, updated_at
`

type CreateCartImportRowParams struct {
	JobID           uuid.UUID   `db:"job_id" json:"job_id"`
	RowNo           int32       `db:"row_no" json:"row_no"`
	RawName         string      `db:"raw_name" json:"raw_name"`
	RawSpec         *string     `db:"raw_spec" json:"raw_spec"`
	RawQty          *string     `db:"raw_qty" json:"raw_qty"`
	MatchType       string      `db:"match_type" json:"match_type"`
	SkuID           pgtype.UUID `db:"sku_id" json:"sku_id"`
	Qty             *int32      `db:"qty" json:"qty"`
	CandidateSkuIds []uuid.UUID `db:"candidate_sku_ids" json:"candidate_sku_ids"`
	SelectedSkuID   pgtype.UUID `db:"selected_sku_id" json:"selected_sku_id"`
	SelectedQty     *int32      `db:"selected_qty" json:"selected_qty"`
}

func (q *Queries) CreateCartImportRow(ctx context.Context, arg CreateCartImportRowParams) (CartImportRow, error) {
	row := q.db.QueryRow(ctx, createCartImportRow,
		arg.JobID,
		arg.RowNo,
		arg.RawName,
		arg.RawSpec,
		arg.RawQty,
		arg.MatchType,
		arg.SkuID,
		arg.Qty,
		arg.CandidateSkuIds,
		arg.SelectedSkuID,
		arg.SelectedQty,
	)
	var i CartImportRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.RowNo,
		&i.RawName,
		&i.RawSpec,
		&i.RawQty,
		&i.MatchType,
		&i.SkuID,
		&i.Qty,
		&i.CandidateSkuIds,
		&i.SelectedSkuID,
		&i.SelectedQty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartImportJob = `-- name: GetCartImportJob :one
SELECT id, owner_user_id, status, progress, auto_added_count, pending_count, created_at, updated_at
FROM cart_import_jobs
WHERE id = $1
`

func (q *Queries) GetCartImportJob(ctx context.Context, id uuid.UUID) (CartImportJob, error) {
	row := q.db.QueryRow(ctx, getCartImportJob, id)
	var i CartImportJob
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Status,
		&i.Progress,
		&i.AutoAddedCount,
		&i.PendingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartImportRows = `-- name: ListCartImportRows :many
SELECT id, job_id, row_no, raw_name, raw_spec, raw_qty, match_type, sku_id, qty, candidate_sku_ids, selected_sku_id, selected_qty, created_at, updated_at
FROM cart_import_rows
WHERE job_id = $1
ORDER BY row_no ASC
`

func (q *Queries) ListCartImportRows(ctx context.Context, jobID uuid.UUID) ([]CartImportRow, error) {
	rows, err := q.db.Query(ctx, listCartImportRows, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartImportRow
	for rows.Next() {
		var i CartImportRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RowNo,
			&i.RawName,
			&i.RawSpec,
			&i.RawQty,
			&i.MatchType,
			&i.SkuID,
			&i.Qty,
			&i.CandidateSkuIds,
			&i.SelectedSkuID,
			&i.SelectedQty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartImportJobCounts = `-- name: UpdateCartImportJobCounts :exec
UPDATE cart_import_jobs
SET auto_added_count = $2,
    pending_count = $3,
    status = $4,
    progress = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateCartImportJobCountsParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	AutoAddedCount int32     `db:"auto_added_count" json:"auto_added_count"`
	PendingCount   int32     `db:"pending_count" json:"pending_count"`
	Status         string    `db:"status" json:"status"`
	Progress       int32     `db:"progress" json:"progress"`
}

func (q *Queries) UpdateCartImportJobCounts(ctx context.Context, arg UpdateCartImportJobCountsParams) error {
	_, err := q.db.Exec(ctx, updateCartImportJobCounts,
		arg.ID,
		arg.AutoAddedCount,
		arg.PendingCount,
		arg.Status,
		arg.Progress,
	)
	return err
}

const updateCartImportRowSelection = `-- name: UpdateCartImportRowSelection :exec
UPDATE cart_import_rows
SET selected_sku_id = $2,
    selected_qty = $3,
    updated_at = now()
WHERE job_id = $1 AND row_no = $4
`

type UpdateCartImportRowSelectionParams struct {
	JobID         uuid.UUID   `db:"job_id" json:"job_id"`
	SelectedSkuID pgtype.UUID `db:"selected_sku_id" json:"selected_sku_id"`
	SelectedQty   *int32      `db:"selected_qty" json:"selected_qty"`
	RowNo         int32       `db:"row_no" json:"row_no"`
}

func (q *Queries) UpdateCartImportRowSelection(ctx context.Context, arg UpdateCartImportRowSelectionParams) error {
	_, err := q.db.Exec(ctx, updateCartImportRowSelection,
		arg.JobID,
		arg.SelectedSkuID,
		arg.SelectedQty,
		arg.RowNo,
	)
	return err
}
