// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM catalog_products
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR category_id = $2)
`

type CountProductsParams struct {
	Q          *string     `db:"q" json:"q"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Q, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO catalog_products (
    name,
    description,
    category_id,
    cover_image_url,
    images,
    tags,
    filter_dimensions
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at
`

type CreateProductParams struct {
	Name             string    `db:"name" json:"name"`
	Description      *string   `db:"description" json:"description"`
	CategoryID       uuid.UUID `db:"category_id" json:"category_id"`
	CoverImageUrl    *string   `db:"cover_image_url" json:"cover_image_url"`
	Images           []string  `db:"images" json:"images"`
	Tags             []string  `db:"tags" json:"tags"`
	FilterDimensions []string  `db:"filter_dimensions" json:"filter_dimensions"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.CoverImageUrl,
		arg.Images,
		arg.Tags,
		arg.FilterDimensions,
	)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.CoverImageUrl,
		&i.Images,
		&i.Tags,
		&i.FilterDimensions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at
FROM catalog_products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.CoverImageUrl,
		&i.Images,
		&i.Tags,
		&i.FilterDimensions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at
FROM catalog_products
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR category_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListProductsParams struct {
	Q          *string     `db:"q" json:"q"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]CatalogProduct, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Q,
		arg.CategoryID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogProduct
	for rows.Next() {
		var i CatalogProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.CoverImageUrl,
			&i.Images,
			&i.Tags,
			&i.FilterDimensions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
