// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_price_tiers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPriceTier = `-- name: CreatePriceTier :one
INSERT INTO catalog_price_tiers (
    sku_id,
    min_qty,
    max_qty,
    unit_price
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, sku_id, min_qty, max_qty, unit_price, created_at, updated_at
`

type CreatePriceTierParams struct {
	SkuID     uuid.UUID `db:"sku_id" json:"sku_id"`
	MinQty    int32     `db:"min_qty" json:"min_qty"`
	MaxQty    *int32    `db:"max_qty" json:"max_qty"`
	UnitPrice float64   `db:"unit_price" json:"unit_price"`
}

func (q *Queries) CreatePriceTier(ctx context.Context, arg CreatePriceTierParams) (CatalogPriceTier, error) {
	row := q.db.QueryRow(ctx, createPriceTier,
		arg.SkuID,
		arg.MinQty,
		arg.MaxQty,
		arg.UnitPrice,
	)
	var i CatalogPriceTier
	err := row.Scan(
		&i.ID,
		&i.SkuID,
		&i.MinQty,
		&i.MaxQty,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPriceTiersBySku = `-- name: ListPriceTiersBySku :many
SELECT id, sku_id, min_qty, max_qty, unit_price, created_at, updated_at
FROM catalog_price_tiers
WHERE sku_id = $1
ORDER BY min_qty ASC
`

func (q *Queries) ListPriceTiersBySku(ctx context.Context, skuID uuid.UUID) ([]CatalogPriceTier, error) {
	rows, err := q.db.Query(ctx, listPriceTiersBySku, skuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogPriceTier
	for rows.Next() {
		var i CatalogPriceTier
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.MinQty,
			&i.MaxQty,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersBySkus = `-- name: ListPriceTiersBySkus :many
SELECT id, sku_id, min_qty, max_qty, unit_price, created_at, updated_at
FROM catalog_price_tiers
WHERE sku_id = ANY($1::uuid[])
ORDER BY sku_id, min_qty ASC
`

func (q *Queries) ListPriceTiersBySkus(ctx context.Context, dollar_1 []uuid.UUID) ([]CatalogPriceTier, error) {
	rows, err := q.db.Query(ctx, listPriceTiersBySkus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogPriceTier
	for rows.Next() {
		var i CatalogPriceTier
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.MinQty,
			&i.MaxQty,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
