// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO catalog_categories (
    name,
    parent_id,
    sort
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, parent_id, sort, created_at, updated_at
`

type CreateCategoryParams struct {
	Name     string      `db:"name" json:"name"`
	ParentID pgtype.UUID `db:"parent_id" json:"parent_id"`
	Sort     int32       `db:"sort" json:"sort"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.ParentID, arg.Sort)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id, sort, created_at, updated_at
FROM catalog_categories
ORDER BY sort ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCategory
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Sort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
