// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
WITH lock_category_sort AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(1984052701)
), target_position AS MATERIALIZED (
    SELECT LEAST(GREATEST($3::integer, 1), count(*)::integer + 1) AS sort
    FROM catalog_categories
    CROSS JOIN lock_category_sort
), shifted AS (
    UPDATE catalog_categories AS category
    SET sort = category.sort + 1,
        updated_at = now()
    FROM target_position
    WHERE category.sort >= target_position.sort
    RETURNING category.id
)
INSERT INTO catalog_categories (
    name,
    parent_id,
    sort
) SELECT
    $1,
    $2,
    target_position.sort
FROM target_position
RETURNING id, name, parent_id, sort, created_at, updated_at
`

type CreateCategoryParams struct {
	Name     string      `db:"name" json:"name"`
	ParentID pgtype.UUID `db:"parent_id" json:"parent_id"`
	Sort     int32       `db:"sort" json:"sort"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.ParentID, arg.Sort)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
WITH lock_category_sort AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(1984052701)
), deleted AS (
    DELETE FROM catalog_categories AS category
    USING lock_category_sort
    WHERE category.id = $1
    RETURNING category.sort
), shifted AS (
    UPDATE catalog_categories AS category
    SET sort = category.sort - 1,
        updated_at = now()
    FROM deleted
    WHERE category.sort > deleted.sort
    RETURNING category.id
)
SELECT count(*)::bigint
FROM deleted
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, parent_id, sort, created_at, updated_at
FROM catalog_categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_id, sort, created_at, updated_at
FROM catalog_categories
ORDER BY sort ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCategory
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Sort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
WITH lock_category_sort AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(1984052701)
), current_category AS MATERIALIZED (
    SELECT category.id, category.sort
    FROM catalog_categories AS category
    CROSS JOIN lock_category_sort
    WHERE category.id = $4
), target_position AS MATERIALIZED (
    SELECT
        current_category.id,
        current_category.sort AS old_sort,
        CASE
            WHEN $5::integer IS NULL THEN current_category.sort
            ELSE LEAST(GREATEST($5::integer, 1), count(*)::integer)
        END AS new_sort
    FROM current_category
    CROSS JOIN catalog_categories
    GROUP BY current_category.id, current_category.sort
), shifted AS (
    UPDATE catalog_categories AS category
    SET sort = CASE
            WHEN target_position.new_sort < target_position.old_sort THEN category.sort + 1
            ELSE category.sort - 1
        END,
        updated_at = now()
    FROM target_position
    WHERE category.id <> target_position.id
      AND (
          (target_position.new_sort < target_position.old_sort
              AND category.sort >= target_position.new_sort
              AND category.sort < target_position.old_sort)
          OR
          (target_position.new_sort > target_position.old_sort
              AND category.sort > target_position.old_sort
              AND category.sort <= target_position.new_sort)
      )
    RETURNING category.id
)
UPDATE catalog_categories AS category
SET name = COALESCE($1::text, category.name),
    parent_id = CASE
        WHEN $2::boolean THEN $3::uuid
        ELSE category.parent_id
    END,
    sort = target_position.new_sort,
    updated_at = now()
FROM target_position
WHERE category.id = target_position.id
RETURNING category.id, category.name, category.parent_id, category.sort, category.created_at, category.updated_at
`

type UpdateCategoryParams struct {
	Name        *string     `db:"name" json:"name"`
	ParentIDSet bool        `db:"parent_id_set" json:"parent_id_set"`
	ParentID    pgtype.UUID `db:"parent_id" json:"parent_id"`
	ID          uuid.UUID   `db:"id" json:"id"`
	Sort        *int32      `db:"sort" json:"sort"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.ParentIDSet,
		arg.ParentID,
		arg.ID,
		arg.Sort,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
