// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM catalog_products
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR category_id = $2)
  AND ($3::text IS NULL OR status = $3)
`

type CountProductsParams struct {
	Q          *string     `db:"q" json:"q"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
	Status     *string     `db:"status" json:"status"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Q, arg.CategoryID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO catalog_products (
    name,
    description,
    category_id,
    cover_image_url,
    images,
    tags,
    filter_dimensions,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at, status
`

type CreateProductParams struct {
	Name             string    `db:"name" json:"name"`
	Description      *string   `db:"description" json:"description"`
	CategoryID       uuid.UUID `db:"category_id" json:"category_id"`
	CoverImageUrl    *string   `db:"cover_image_url" json:"cover_image_url"`
	Images           []string  `db:"images" json:"images"`
	Tags             []string  `db:"tags" json:"tags"`
	FilterDimensions []string  `db:"filter_dimensions" json:"filter_dimensions"`
	Status           string    `db:"status" json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.CoverImageUrl,
		arg.Images,
		arg.Tags,
		arg.FilterDimensions,
		arg.Status,
	)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.CoverImageUrl,
		&i.Images,
		&i.Tags,
		&i.FilterDimensions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
WITH target_skus AS (
    SELECT id
    FROM catalog_skus
    WHERE product_id = $1
),
deleted_cart_items AS (
    DELETE FROM cart_items
    WHERE sku_id IN (SELECT id FROM target_skus)
),
deleted_wishlist_items AS (
    DELETE FROM wishlist_items
    WHERE sku_id IN (SELECT id FROM target_skus)
),
deleted_product AS (
    DELETE FROM catalog_products
    WHERE id = $1
    RETURNING 1
)
SELECT count(*)::bigint
FROM deleted_product
`

func (q *Queries) DeleteProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, deleteProduct, productID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at, status
FROM catalog_products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.CoverImageUrl,
		&i.Images,
		&i.Tags,
		&i.FilterDimensions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at, status
FROM catalog_products
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR category_id = $2)
  AND ($3::text IS NULL OR status = $3)
ORDER BY CASE status
           WHEN 'ACTIVE' THEN 0
           WHEN 'DRAFT' THEN 1
           WHEN 'INACTIVE' THEN 2
           ELSE 3
         END,
         created_at DESC,
         id ASC
LIMIT $5 OFFSET $4
`

type ListProductsParams struct {
	Q          *string     `db:"q" json:"q"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
	Status     *string     `db:"status" json:"status"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]CatalogProduct, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Q,
		arg.CategoryID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogProduct
	for rows.Next() {
		var i CatalogProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.CoverImageUrl,
			&i.Images,
			&i.Tags,
			&i.FilterDimensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE catalog_products
SET name = $2,
    description = $3,
    category_id = $4,
    cover_image_url = $5,
    images = $6,
    tags = $7,
    filter_dimensions = $8,
    status = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, category_id, cover_image_url, images, tags, filter_dimensions, created_at, updated_at, status
`

type UpdateProductParams struct {
	ID               uuid.UUID `db:"id" json:"id"`
	Name             string    `db:"name" json:"name"`
	Description      *string   `db:"description" json:"description"`
	CategoryID       uuid.UUID `db:"category_id" json:"category_id"`
	CoverImageUrl    *string   `db:"cover_image_url" json:"cover_image_url"`
	Images           []string  `db:"images" json:"images"`
	Tags             []string  `db:"tags" json:"tags"`
	FilterDimensions []string  `db:"filter_dimensions" json:"filter_dimensions"`
	Status           string    `db:"status" json:"status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.CoverImageUrl,
		arg.Images,
		arg.Tags,
		arg.FilterDimensions,
		arg.Status,
	)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.CoverImageUrl,
		&i.Images,
		&i.Tags,
		&i.FilterDimensions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
