// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_skus.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createSku = `-- name: CreateSku :one
INSERT INTO catalog_skus (
    product_id,
    sku_code,
    name,
    attributes,
    unit,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, product_id, sku_code, name, attributes, unit, is_active, created_at, updated_at
`

type CreateSkuParams struct {
	ProductID  uuid.UUID       `db:"product_id" json:"product_id"`
	SkuCode    *string         `db:"sku_code" json:"sku_code"`
	Name       string          `db:"name" json:"name"`
	Attributes json.RawMessage `db:"attributes" json:"attributes"`
	Unit       *string         `db:"unit" json:"unit"`
	IsActive   bool            `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateSku(ctx context.Context, arg CreateSkuParams) (CatalogSku, error) {
	row := q.db.QueryRow(ctx, createSku,
		arg.ProductID,
		arg.SkuCode,
		arg.Name,
		arg.Attributes,
		arg.Unit,
		arg.IsActive,
	)
	var i CatalogSku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SkuCode,
		&i.Name,
		&i.Attributes,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkusByIDs = `-- name: ListSkusByIDs :many
SELECT id, product_id, sku_code, name, attributes, unit, is_active, created_at, updated_at
FROM catalog_skus
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListSkusByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]CatalogSku, error) {
	rows, err := q.db.Query(ctx, listSkusByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogSku
	for rows.Next() {
		var i CatalogSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Name,
			&i.Attributes,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkusByName = `-- name: ListSkusByName :many
SELECT id, product_id, sku_code, name, attributes, unit, is_active, created_at, updated_at
FROM catalog_skus
WHERE name = $1
`

func (q *Queries) ListSkusByName(ctx context.Context, name string) ([]CatalogSku, error) {
	rows, err := q.db.Query(ctx, listSkusByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogSku
	for rows.Next() {
		var i CatalogSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Name,
			&i.Attributes,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkusByNameAndSpec = `-- name: ListSkusByNameAndSpec :many
SELECT id, product_id, sku_code, name, attributes, unit, is_active, created_at, updated_at
FROM catalog_skus
WHERE name = $1
  AND attributes->>'spec' = $2
`

type ListSkusByNameAndSpecParams struct {
	Name       string          `db:"name" json:"name"`
	Attributes json.RawMessage `db:"attributes" json:"attributes"`
}

func (q *Queries) ListSkusByNameAndSpec(ctx context.Context, arg ListSkusByNameAndSpecParams) ([]CatalogSku, error) {
	rows, err := q.db.Query(ctx, listSkusByNameAndSpec, arg.Name, arg.Attributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogSku
	for rows.Next() {
		var i CatalogSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Name,
			&i.Attributes,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkusByProduct = `-- name: ListSkusByProduct :many
SELECT id, product_id, sku_code, name, attributes, unit, is_active, created_at, updated_at
FROM catalog_skus
WHERE product_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSkusByProduct(ctx context.Context, productID uuid.UUID) ([]CatalogSku, error) {
	rows, err := q.db.Query(ctx, listSkusByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogSku
	for rows.Next() {
		var i CatalogSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Name,
			&i.Attributes,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkusBySkuCode = `-- name: ListSkusBySkuCode :many
SELECT id, product_id, sku_code, name, attributes, unit, is_active, created_at, updated_at
FROM catalog_skus
WHERE sku_code = $1
`

func (q *Queries) ListSkusBySkuCode(ctx context.Context, skuCode *string) ([]CatalogSku, error) {
	rows, err := q.db.Query(ctx, listSkusBySkuCode, skuCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogSku
	for rows.Next() {
		var i CatalogSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Name,
			&i.Attributes,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
