// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (
    type,
    status,
    progress,
    result_file_url,
    error_report_url,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, type, status, progress, result_file_url, error_report_url, created_by_user_id, created_at
`

type CreateImportJobParams struct {
	Type            string      `db:"type" json:"type"`
	Status          string      `db:"status" json:"status"`
	Progress        int32       `db:"progress" json:"progress"`
	ResultFileUrl   *string     `db:"result_file_url" json:"result_file_url"`
	ErrorReportUrl  *string     `db:"error_report_url" json:"error_report_url"`
	CreatedByUserID pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.Type,
		arg.Status,
		arg.Progress,
		arg.ResultFileUrl,
		arg.ErrorReportUrl,
		arg.CreatedByUserID,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.ResultFileUrl,
		&i.ErrorReportUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
