// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSupplier struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	SupplierCode         string             `db:"supplier_code" json:"supplier_code"`
	Name                 string             `db:"name" json:"name"`
	Country              string             `db:"country" json:"country"`
	City                 string             `db:"city" json:"city"`
	Categories           []string           `db:"categories" json:"categories"`
	Status               string             `db:"status" json:"status"`
	Score                int32              `db:"score" json:"score"`
	LastQuoteAmountCents *int64             `db:"last_quote_amount_cents" json:"last_quote_amount_cents"`
	LastQuoteAt          pgtype.Timestamptz `db:"last_quote_at" json:"last_quote_at"`
	Notes                string             `db:"notes" json:"notes"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AdminSupplierContact struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	SupplierID uuid.UUID          `db:"supplier_id" json:"supplier_id"`
	Name       string             `db:"name" json:"name"`
	Title      string             `db:"title" json:"title"`
	Email      *string            `db:"email" json:"email"`
	Phone      *string            `db:"phone" json:"phone"`
	IsPrimary  bool               `db:"is_primary" json:"is_primary"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AdminSupplierScorecard struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	SupplierID    uuid.UUID          `db:"supplier_id" json:"supplier_id"`
	Period        string             `db:"period" json:"period"`
	DeliveryScore int32              `db:"delivery_score" json:"delivery_score"`
	QualityScore  int32              `db:"quality_score" json:"quality_score"`
	PriceScore    int32              `db:"price_score" json:"price_score"`
	RiskLevel     string             `db:"risk_level" json:"risk_level"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AfterSalesMessage struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TicketID     uuid.UUID          `db:"ticket_id" json:"ticket_id"`
	SenderType   string             `db:"sender_type" json:"sender_type"`
	SenderUserID pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AfterSalesTicket struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	Status              string             `db:"status" json:"status"`
	OrderID             pgtype.UUID        `db:"order_id" json:"order_id"`
	CreatedByUserID     uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	OwnerSalesUserID    pgtype.UUID        `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	AssignedStaffUserID pgtype.UUID        `db:"assigned_staff_user_id" json:"assigned_staff_user_id"`
	Subject             string             `db:"subject" json:"subject"`
	Description         string             `db:"description" json:"description"`
	Attachments         []string           `db:"attachments" json:"attachments"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CartImportJob struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OwnerUserID    uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	Status         string             `db:"status" json:"status"`
	Progress       int32              `db:"progress" json:"progress"`
	AutoAddedCount int32              `db:"auto_added_count" json:"auto_added_count"`
	PendingCount   int32              `db:"pending_count" json:"pending_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CartImportRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	RowNo           int32              `db:"row_no" json:"row_no"`
	RawName         string             `db:"raw_name" json:"raw_name"`
	RawSpec         *string            `db:"raw_spec" json:"raw_spec"`
	RawQty          *string            `db:"raw_qty" json:"raw_qty"`
	MatchType       string             `db:"match_type" json:"match_type"`
	SkuID           pgtype.UUID        `db:"sku_id" json:"sku_id"`
	Qty             *int32             `db:"qty" json:"qty"`
	CandidateSkuIds []uuid.UUID        `db:"candidate_sku_ids" json:"candidate_sku_ids"`
	SelectedSkuID   pgtype.UUID        `db:"selected_sku_id" json:"selected_sku_id"`
	SelectedQty     *int32             `db:"selected_qty" json:"selected_qty"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CartItem struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	OwnerUserID uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	SkuID       uuid.UUID          `db:"sku_id" json:"sku_id"`
	Qty         int32              `db:"qty" json:"qty"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogCategory struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parent_id"`
	Sort      int32              `db:"sort" json:"sort"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogMediaAsset struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ProductID     uuid.UUID          `db:"product_id" json:"product_id"`
	SourceUrl     string             `db:"source_url" json:"source_url"`
	StorageUrl    *string            `db:"storage_url" json:"storage_url"`
	ContentSha256 *string            `db:"content_sha256" json:"content_sha256"`
	Status        string             `db:"status" json:"status"`
	ErrorMessage  *string            `db:"error_message" json:"error_message"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogPriceTier struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	SkuID        uuid.UUID          `db:"sku_id" json:"sku_id"`
	MinQty       int32              `db:"min_qty" json:"min_qty"`
	MaxQty       *int32             `db:"max_qty" json:"max_qty"`
	UnitPriceFen int64              `db:"unit_price_fen" json:"unit_price_fen"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogProduct struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Description      *string            `db:"description" json:"description"`
	CategoryID       uuid.UUID          `db:"category_id" json:"category_id"`
	CoverImageUrl    *string            `db:"cover_image_url" json:"cover_image_url"`
	Images           []string           `db:"images" json:"images"`
	Tags             []string           `db:"tags" json:"tags"`
	FilterDimensions []string           `db:"filter_dimensions" json:"filter_dimensions"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CatalogSku struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ProductID  uuid.UUID          `db:"product_id" json:"product_id"`
	SkuCode    *string            `db:"sku_code" json:"sku_code"`
	Name       string             `db:"name" json:"name"`
	Spec       *string            `db:"spec" json:"spec"`
	Attributes json.RawMessage    `db:"attributes" json:"attributes"`
	Unit       *string            `db:"unit" json:"unit"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ImportJob struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Type            string             `db:"type" json:"type"`
	Status          string             `db:"status" json:"status"`
	Progress        int32              `db:"progress" json:"progress"`
	ResultFileUrl   *string            `db:"result_file_url" json:"result_file_url"`
	ErrorReportUrl  *string            `db:"error_report_url" json:"error_report_url"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InquiryMessage struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	InquiryID    uuid.UUID          `db:"inquiry_id" json:"inquiry_id"`
	SenderType   string             `db:"sender_type" json:"sender_type"`
	SenderUserID pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MiniappDisplayCategory struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	IconKey   string             `db:"icon_key" json:"icon_key"`
	Sort      int32              `db:"sort" json:"sort"`
	Enabled   bool               `db:"enabled" json:"enabled"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Order struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Status           string             `db:"status" json:"status"`
	CustomerID       uuid.UUID          `db:"customer_id" json:"customer_id"`
	OwnerSalesUserID pgtype.UUID        `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Address          json.RawMessage    `db:"address" json:"address"`
	Remark           *string            `db:"remark" json:"remark"`
	IdempotencyKey   *string            `db:"idempotency_key" json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PaymentStatus    string             `db:"payment_status" json:"payment_status"`
	LatestPaymentID  pgtype.UUID        `db:"latest_payment_id" json:"latest_payment_id"`
	PaymentChannel   *string            `db:"payment_channel" json:"payment_channel"`
	PaidAt           pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
}

type OrderItem struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	OrderID          uuid.UUID          `db:"order_id" json:"order_id"`
	SkuID            uuid.UUID          `db:"sku_id" json:"sku_id"`
	Qty              int32              `db:"qty" json:"qty"`
	UnitPriceFen     int64              `db:"unit_price_fen" json:"unit_price_fen"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceCartItemID pgtype.UUID        `db:"source_cart_item_id" json:"source_cart_item_id"`
}

type OrderTrackingShipment struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	OrderID   uuid.UUID          `db:"order_id" json:"order_id"`
	WaybillNo string             `db:"waybill_no" json:"waybill_no"`
	Carrier   *string            `db:"carrier" json:"carrier"`
	ShippedAt pgtype.Timestamptz `db:"shipped_at" json:"shipped_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PriceInquiry struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CreatedByUserID     uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	OwnerSalesUserID    pgtype.UUID        `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	AssignedSalesUserID pgtype.UUID        `db:"assigned_sales_user_id" json:"assigned_sales_user_id"`
	SkuID               pgtype.UUID        `db:"sku_id" json:"sku_id"`
	OrderID             pgtype.UUID        `db:"order_id" json:"order_id"`
	Message             string             `db:"message" json:"message"`
	Status              string             `db:"status" json:"status"`
	ResponseNote        *string            `db:"response_note" json:"response_note"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductImportJob struct {
	JobID         uuid.UUID          `db:"job_id" json:"job_id"`
	ExcelFilePath string             `db:"excel_file_path" json:"excel_file_path"`
	ExcelFileName string             `db:"excel_file_name" json:"excel_file_name"`
	ImagesZipPath *string            `db:"images_zip_path" json:"images_zip_path"`
	ImagesZipName *string            `db:"images_zip_name" json:"images_zip_name"`
	ImageBaseUrl  *string            `db:"image_base_url" json:"image_base_url"`
	TotalRows     int32              `db:"total_rows" json:"total_rows"`
	SuccessRows   int32              `db:"success_rows" json:"success_rows"`
	FailedRows    int32              `db:"failed_rows" json:"failed_rows"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductImportRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	JobID        uuid.UUID          `db:"job_id" json:"job_id"`
	LineNo       int32              `db:"line_no" json:"line_no"`
	GroupKey     *string            `db:"group_key" json:"group_key"`
	SkuCode      *string            `db:"sku_code" json:"sku_code"`
	ProductName  *string            `db:"product_name" json:"product_name"`
	RowData      json.RawMessage    `db:"row_data" json:"row_data"`
	Status       string             `db:"status" json:"status"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	ProductID    pgtype.UUID        `db:"product_id" json:"product_id"`
	SkuID        pgtype.UUID        `db:"sku_id" json:"sku_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductRequest struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	CreatedByUserID    uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	OwnerSalesUserID   pgtype.UUID        `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Name               string             `db:"name" json:"name"`
	Spec               *string            `db:"spec" json:"spec"`
	Qty                *string            `db:"qty" json:"qty"`
	Note               *string            `db:"note" json:"note"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryID         pgtype.UUID        `db:"category_id" json:"category_id"`
	Material           *string            `db:"material" json:"material"`
	Dimensions         *string            `db:"dimensions" json:"dimensions"`
	Color              *string            `db:"color" json:"color"`
	ReferenceImageUrls []string           `db:"reference_image_urls" json:"reference_image_urls"`
}

type ProductRequestExportJob struct {
	JobID         uuid.UUID          `db:"job_id" json:"job_id"`
	CreatedAfter  pgtype.Timestamptz `db:"created_after" json:"created_after"`
	CreatedBefore pgtype.Timestamptz `db:"created_before" json:"created_before"`
	ExportedRows  int32              `db:"exported_rows" json:"exported_rows"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SupportConversation struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	CustomerUserID      uuid.UUID          `db:"customer_user_id" json:"customer_user_id"`
	OwnerSalesUserID    pgtype.UUID        `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	AssigneeUserID      pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole        *string            `db:"assignee_role" json:"assignee_role"`
	Status              string             `db:"status" json:"status"`
	LastMessageType     *string            `db:"last_message_type" json:"last_message_type"`
	LastMessagePreview  *string            `db:"last_message_preview" json:"last_message_preview"`
	LastMessageAt       pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
	CustomerUnreadCount int32              `db:"customer_unread_count" json:"customer_unread_count"`
	StaffUnreadCount    int32              `db:"staff_unread_count" json:"staff_unread_count"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ClosedAt            pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
}

type SupportConversationTransfer struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ConversationID  uuid.UUID          `db:"conversation_id" json:"conversation_id"`
	FromUserID      pgtype.UUID        `db:"from_user_id" json:"from_user_id"`
	FromRole        *string            `db:"from_role" json:"from_role"`
	ToUserID        uuid.UUID          `db:"to_user_id" json:"to_user_id"`
	ToRole          string             `db:"to_role" json:"to_role"`
	Note            *string            `db:"note" json:"note"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SupportMessage struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ConversationID uuid.UUID          `db:"conversation_id" json:"conversation_id"`
	SenderType     string             `db:"sender_type" json:"sender_type"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	SenderRole     *string            `db:"sender_role" json:"sender_role"`
	MessageType    string             `db:"message_type" json:"message_type"`
	TextContent    *string            `db:"text_content" json:"text_content"`
	AssetID        pgtype.UUID        `db:"asset_id" json:"asset_id"`
	CardPayload    []byte             `db:"card_payload" json:"card_payload"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SupportMessageAsset struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ConversationID   uuid.UUID          `db:"conversation_id" json:"conversation_id"`
	UploadedByUserID uuid.UUID          `db:"uploaded_by_user_id" json:"uploaded_by_user_id"`
	ContentType      string             `db:"content_type" json:"content_type"`
	FileName         string             `db:"file_name" json:"file_name"`
	FileSize         int64              `db:"file_size" json:"file_size"`
	Url              string             `db:"url" json:"url"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserAddress struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	ReceiverName  string             `db:"receiver_name" json:"receiver_name"`
	ReceiverPhone string             `db:"receiver_phone" json:"receiver_phone"`
	Detail        string             `db:"detail" json:"detail"`
	IsDefault     bool               `db:"is_default" json:"is_default"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WishlistItem struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	OwnerUserID uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	SkuID       uuid.UUID          `db:"sku_id" json:"sku_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
