// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT count(*)
FROM orders
WHERE ($1::uuid IS NULL OR customer_id = $1)
  AND ($2::uuid IS NULL OR owner_sales_user_id = $2)
  AND ($3::text IS NULL OR status = $3)
`

type CountOrdersParams struct {
	CustomerID       pgtype.UUID `db:"customer_id" json:"customer_id"`
	OwnerSalesUserID pgtype.UUID `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Status           *string     `db:"status" json:"status"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.CustomerID, arg.OwnerSalesUserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    status,
    customer_id,
    owner_sales_user_id,
    address,
    remark,
    idempotency_key
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, status, customer_id, owner_sales_user_id, address, remark, idempotency_key, created_at, updated_at
`

type CreateOrderParams struct {
	Status           string          `db:"status" json:"status"`
	CustomerID       uuid.UUID       `db:"customer_id" json:"customer_id"`
	OwnerSalesUserID pgtype.UUID     `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Address          json.RawMessage `db:"address" json:"address"`
	Remark           *string         `db:"remark" json:"remark"`
	IdempotencyKey   *string         `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Status,
		arg.CustomerID,
		arg.OwnerSalesUserID,
		arg.Address,
		arg.Remark,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CustomerID,
		&i.OwnerSalesUserID,
		&i.Address,
		&i.Remark,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    sku_id,
    qty,
    unit_price_fen
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, order_id, sku_id, qty, unit_price_fen, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID      uuid.UUID `db:"order_id" json:"order_id"`
	SkuID        uuid.UUID `db:"sku_id" json:"sku_id"`
	Qty          int32     `db:"qty" json:"qty"`
	UnitPriceFen int64     `db:"unit_price_fen" json:"unit_price_fen"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.SkuID,
		arg.Qty,
		arg.UnitPriceFen,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SkuID,
		&i.Qty,
		&i.UnitPriceFen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, status, customer_id, owner_sales_user_id, address, remark, idempotency_key, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CustomerID,
		&i.OwnerSalesUserID,
		&i.Address,
		&i.Remark,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, status, customer_id, owner_sales_user_id, address, remark, idempotency_key, created_at, updated_at
FROM orders
WHERE customer_id = $1 AND idempotency_key = $2
`

type GetOrderByIdempotencyKeyParams struct {
	CustomerID     uuid.UUID `db:"customer_id" json:"customer_id"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, arg.CustomerID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CustomerID,
		&i.OwnerSalesUserID,
		&i.Address,
		&i.Remark,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, sku_id, qty, unit_price_fen, created_at, updated_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SkuID,
			&i.Qty,
			&i.UnitPriceFen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, status, customer_id, owner_sales_user_id, address, remark, idempotency_key, created_at, updated_at
FROM orders
WHERE ($1::uuid IS NULL OR customer_id = $1)
  AND ($2::uuid IS NULL OR owner_sales_user_id = $2)
  AND ($3::text IS NULL OR status = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListOrdersParams struct {
	CustomerID       pgtype.UUID `db:"customer_id" json:"customer_id"`
	OwnerSalesUserID pgtype.UUID `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Status           *string     `db:"status" json:"status"`
	Offset           int32       `db:"offset" json:"offset"`
	Limit            int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.CustomerID,
		arg.OwnerSalesUserID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CustomerID,
			&i.OwnerSalesUserID,
			&i.Address,
			&i.Remark,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
