// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_import_lifecycle.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimProductImportLifecycle = `-- name: ClaimProductImportLifecycle :one
WITH candidate AS (
    SELECT pj.job_id FROM product_import_jobs pj JOIN import_jobs ij ON ij.id = pj.job_id
    WHERE ij.type = 'PRODUCT_IMPORT'
      AND ((ij.status = 'PENDING' AND pj.phase IN ('VALIDATE_PENDING', 'COMMIT_PENDING'))
        OR (ij.status = 'RUNNING' AND pj.phase IN ('VALIDATING', 'COMMITTING')
            AND (pj.lease_expires_at IS NULL OR pj.lease_expires_at < now())))
    ORDER BY ij.created_at, ij.id FOR UPDATE OF pj SKIP LOCKED LIMIT 1
), claimed AS (
    UPDATE product_import_jobs pj
    SET lease_token = gen_random_uuid(), lease_expires_at = now() + interval '60 seconds',
        phase = CASE WHEN pj.phase IN ('COMMIT_PENDING', 'COMMITTING') THEN 'COMMITTING' ELSE 'VALIDATING' END,
        updated_at = now()
    FROM candidate WHERE pj.job_id = candidate.job_id RETURNING pj.job_id, pj.excel_file_path, pj.excel_file_name, pj.images_zip_path, pj.images_zip_name, pj.image_base_url, pj.total_rows, pj.success_rows, pj.failed_rows, pj.created_at, pj.updated_at, pj.source_format, pj.source_namespace, pj.phase, pj.preview_revision, pj.summary, pj.lease_token, pj.lease_expires_at, pj.confirmed_revision, pj.confirmed_by_user_id, pj.confirm_idempotency_key
), base AS (
    UPDATE import_jobs ij SET status = 'RUNNING', updated_at = now()
    FROM claimed WHERE ij.id = claimed.job_id RETURNING ij.id
)
SELECT claimed.job_id, claimed.excel_file_path, claimed.excel_file_name, claimed.images_zip_path, claimed.images_zip_name, claimed.image_base_url, claimed.total_rows, claimed.success_rows, claimed.failed_rows, claimed.created_at, claimed.updated_at, claimed.source_format, claimed.source_namespace, claimed.phase, claimed.preview_revision, claimed.summary, claimed.lease_token, claimed.lease_expires_at, claimed.confirmed_revision, claimed.confirmed_by_user_id, claimed.confirm_idempotency_key FROM claimed JOIN base ON base.id = claimed.job_id
`

type ClaimProductImportLifecycleRow struct {
	JobID                 uuid.UUID          `db:"job_id" json:"job_id"`
	ExcelFilePath         string             `db:"excel_file_path" json:"excel_file_path"`
	ExcelFileName         string             `db:"excel_file_name" json:"excel_file_name"`
	ImagesZipPath         *string            `db:"images_zip_path" json:"images_zip_path"`
	ImagesZipName         *string            `db:"images_zip_name" json:"images_zip_name"`
	ImageBaseUrl          *string            `db:"image_base_url" json:"image_base_url"`
	TotalRows             int32              `db:"total_rows" json:"total_rows"`
	SuccessRows           int32              `db:"success_rows" json:"success_rows"`
	FailedRows            int32              `db:"failed_rows" json:"failed_rows"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceFormat          string             `db:"source_format" json:"source_format"`
	SourceNamespace       string             `db:"source_namespace" json:"source_namespace"`
	Phase                 string             `db:"phase" json:"phase"`
	PreviewRevision       int32              `db:"preview_revision" json:"preview_revision"`
	Summary               json.RawMessage    `db:"summary" json:"summary"`
	LeaseToken            pgtype.UUID        `db:"lease_token" json:"lease_token"`
	LeaseExpiresAt        pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	ConfirmedRevision     *int32             `db:"confirmed_revision" json:"confirmed_revision"`
	ConfirmedByUserID     pgtype.UUID        `db:"confirmed_by_user_id" json:"confirmed_by_user_id"`
	ConfirmIdempotencyKey *string            `db:"confirm_idempotency_key" json:"confirm_idempotency_key"`
}

func (q *Queries) ClaimProductImportLifecycle(ctx context.Context) (ClaimProductImportLifecycleRow, error) {
	row := q.db.QueryRow(ctx, claimProductImportLifecycle)
	var i ClaimProductImportLifecycleRow
	err := row.Scan(
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceFormat,
		&i.SourceNamespace,
		&i.Phase,
		&i.PreviewRevision,
		&i.Summary,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.ConfirmedRevision,
		&i.ConfirmedByUserID,
		&i.ConfirmIdempotencyKey,
	)
	return i, err
}

const countPendingProductImportReviews = `-- name: CountPendingProductImportReviews :one
SELECT count(*) FROM product_import_reviews WHERE product_id = $1 AND status = 'PENDING'
`

func (q *Queries) CountPendingProductImportReviews(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingProductImportReviews, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductImportReview = `-- name: CreateProductImportReview :exec
INSERT INTO product_import_reviews (job_id,product_id,sku_id,source_namespace,source_product_key,source_sku_key,source_fingerprint,source_sheet,source_row,code,message,raw_values)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT (source_namespace,source_product_key,source_sku_key,source_fingerprint,code) DO NOTHING
`

type CreateProductImportReviewParams struct {
	JobID             uuid.UUID       `db:"job_id" json:"job_id"`
	ProductID         uuid.UUID       `db:"product_id" json:"product_id"`
	SkuID             pgtype.UUID     `db:"sku_id" json:"sku_id"`
	SourceNamespace   string          `db:"source_namespace" json:"source_namespace"`
	SourceProductKey  string          `db:"source_product_key" json:"source_product_key"`
	SourceSkuKey      string          `db:"source_sku_key" json:"source_sku_key"`
	SourceFingerprint string          `db:"source_fingerprint" json:"source_fingerprint"`
	SourceSheet       string          `db:"source_sheet" json:"source_sheet"`
	SourceRow         int32           `db:"source_row" json:"source_row"`
	Code              string          `db:"code" json:"code"`
	Message           string          `db:"message" json:"message"`
	RawValues         json.RawMessage `db:"raw_values" json:"raw_values"`
}

func (q *Queries) CreateProductImportReview(ctx context.Context, arg CreateProductImportReviewParams) error {
	_, err := q.db.Exec(ctx, createProductImportReview,
		arg.JobID,
		arg.ProductID,
		arg.SkuID,
		arg.SourceNamespace,
		arg.SourceProductKey,
		arg.SourceSkuKey,
		arg.SourceFingerprint,
		arg.SourceSheet,
		arg.SourceRow,
		arg.Code,
		arg.Message,
		arg.RawValues,
	)
	return err
}

const getProductImportLifecycle = `-- name: GetProductImportLifecycle :one
SELECT job_id, excel_file_path, excel_file_name, images_zip_path, images_zip_name, image_base_url, total_rows, success_rows, failed_rows, created_at, updated_at, source_format, source_namespace, phase, preview_revision, summary, lease_token, lease_expires_at, confirmed_revision, confirmed_by_user_id, confirm_idempotency_key FROM product_import_jobs WHERE job_id = $1
`

func (q *Queries) GetProductImportLifecycle(ctx context.Context, jobID uuid.UUID) (ProductImportJob, error) {
	row := q.db.QueryRow(ctx, getProductImportLifecycle, jobID)
	var i ProductImportJob
	err := row.Scan(
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceFormat,
		&i.SourceNamespace,
		&i.Phase,
		&i.PreviewRevision,
		&i.Summary,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.ConfirmedRevision,
		&i.ConfirmedByUserID,
		&i.ConfirmIdempotencyKey,
	)
	return i, err
}

const getProductImportSourceRef = `-- name: GetProductImportSourceRef :one
SELECT source_namespace, source_product_key, source_sku_key, source_fingerprint, product_id, sku_id, first_job_id, last_job_id, created_at, updated_at, source_product_fingerprint, original_source_product_key FROM product_import_source_refs
WHERE source_namespace = $1 AND source_product_key = $2 AND source_sku_key = $3
`

type GetProductImportSourceRefParams struct {
	SourceNamespace  string `db:"source_namespace" json:"source_namespace"`
	SourceProductKey string `db:"source_product_key" json:"source_product_key"`
	SourceSkuKey     string `db:"source_sku_key" json:"source_sku_key"`
}

func (q *Queries) GetProductImportSourceRef(ctx context.Context, arg GetProductImportSourceRefParams) (ProductImportSourceRef, error) {
	row := q.db.QueryRow(ctx, getProductImportSourceRef, arg.SourceNamespace, arg.SourceProductKey, arg.SourceSkuKey)
	var i ProductImportSourceRef
	err := row.Scan(
		&i.SourceNamespace,
		&i.SourceProductKey,
		&i.SourceSkuKey,
		&i.SourceFingerprint,
		&i.ProductID,
		&i.SkuID,
		&i.FirstJobID,
		&i.LastJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceProductFingerprint,
		&i.OriginalSourceProductKey,
	)
	return i, err
}

const getProductImportSourceSKU = `-- name: GetProductImportSourceSKU :one
SELECT source_namespace, source_product_key, source_sku_key, source_fingerprint, product_id, sku_id, first_job_id, last_job_id, created_at, updated_at, source_product_fingerprint, original_source_product_key FROM product_import_source_refs WHERE source_namespace = $1 AND source_sku_key = $2
`

type GetProductImportSourceSKUParams struct {
	SourceNamespace string `db:"source_namespace" json:"source_namespace"`
	SourceSkuKey    string `db:"source_sku_key" json:"source_sku_key"`
}

func (q *Queries) GetProductImportSourceSKU(ctx context.Context, arg GetProductImportSourceSKUParams) (ProductImportSourceRef, error) {
	row := q.db.QueryRow(ctx, getProductImportSourceSKU, arg.SourceNamespace, arg.SourceSkuKey)
	var i ProductImportSourceRef
	err := row.Scan(
		&i.SourceNamespace,
		&i.SourceProductKey,
		&i.SourceSkuKey,
		&i.SourceFingerprint,
		&i.ProductID,
		&i.SkuID,
		&i.FirstJobID,
		&i.LastJobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceProductFingerprint,
		&i.OriginalSourceProductKey,
	)
	return i, err
}

const heartbeatProductImportLifecycle = `-- name: HeartbeatProductImportLifecycle :execrows
UPDATE product_import_jobs SET lease_expires_at = now() + interval '60 seconds', updated_at = now()
WHERE job_id = $1 AND lease_token = $2 AND lease_expires_at > now()
  AND phase IN ('VALIDATING', 'COMMITTING')
`

type HeartbeatProductImportLifecycleParams struct {
	JobID      uuid.UUID   `db:"job_id" json:"job_id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) HeartbeatProductImportLifecycle(ctx context.Context, arg HeartbeatProductImportLifecycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatProductImportLifecycle, arg.JobID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProductImportSourceFamily = `-- name: ListProductImportSourceFamily :many
SELECT source_namespace, source_product_key, source_sku_key, source_fingerprint, product_id, sku_id, first_job_id, last_job_id, created_at, updated_at, source_product_fingerprint, original_source_product_key FROM product_import_source_refs WHERE source_namespace = $1 AND original_source_product_key = $2
`

type ListProductImportSourceFamilyParams struct {
	SourceNamespace          string `db:"source_namespace" json:"source_namespace"`
	OriginalSourceProductKey string `db:"original_source_product_key" json:"original_source_product_key"`
}

func (q *Queries) ListProductImportSourceFamily(ctx context.Context, arg ListProductImportSourceFamilyParams) ([]ProductImportSourceRef, error) {
	rows, err := q.db.Query(ctx, listProductImportSourceFamily, arg.SourceNamespace, arg.OriginalSourceProductKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImportSourceRef
	for rows.Next() {
		var i ProductImportSourceRef
		if err := rows.Scan(
			&i.SourceNamespace,
			&i.SourceProductKey,
			&i.SourceSkuKey,
			&i.SourceFingerprint,
			&i.ProductID,
			&i.SkuID,
			&i.FirstJobID,
			&i.LastJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceProductFingerprint,
			&i.OriginalSourceProductKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImportSourceGroup = `-- name: ListProductImportSourceGroup :many
SELECT source_namespace, source_product_key, source_sku_key, source_fingerprint, product_id, sku_id, first_job_id, last_job_id, created_at, updated_at, source_product_fingerprint, original_source_product_key FROM product_import_source_refs WHERE source_namespace = $1 AND source_product_key = $2
`

type ListProductImportSourceGroupParams struct {
	SourceNamespace  string `db:"source_namespace" json:"source_namespace"`
	SourceProductKey string `db:"source_product_key" json:"source_product_key"`
}

func (q *Queries) ListProductImportSourceGroup(ctx context.Context, arg ListProductImportSourceGroupParams) ([]ProductImportSourceRef, error) {
	rows, err := q.db.Query(ctx, listProductImportSourceGroup, arg.SourceNamespace, arg.SourceProductKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImportSourceRef
	for rows.Next() {
		var i ProductImportSourceRef
		if err := rows.Scan(
			&i.SourceNamespace,
			&i.SourceProductKey,
			&i.SourceSkuKey,
			&i.SourceFingerprint,
			&i.ProductID,
			&i.SkuID,
			&i.FirstJobID,
			&i.LastJobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceProductFingerprint,
			&i.OriginalSourceProductKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProductImportLifecycle = `-- name: LockProductImportLifecycle :one
SELECT job_id, excel_file_path, excel_file_name, images_zip_path, images_zip_name, image_base_url, total_rows, success_rows, failed_rows, created_at, updated_at, source_format, source_namespace, phase, preview_revision, summary, lease_token, lease_expires_at, confirmed_revision, confirmed_by_user_id, confirm_idempotency_key FROM product_import_jobs WHERE job_id = $1 FOR UPDATE
`

func (q *Queries) LockProductImportLifecycle(ctx context.Context, jobID uuid.UUID) (ProductImportJob, error) {
	row := q.db.QueryRow(ctx, lockProductImportLifecycle, jobID)
	var i ProductImportJob
	err := row.Scan(
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceFormat,
		&i.SourceNamespace,
		&i.Phase,
		&i.PreviewRevision,
		&i.Summary,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.ConfirmedRevision,
		&i.ConfirmedByUserID,
		&i.ConfirmIdempotencyKey,
	)
	return i, err
}

const upsertProductImportSourceRef = `-- name: UpsertProductImportSourceRef :exec
INSERT INTO product_import_source_refs (source_namespace,source_product_key,source_sku_key,source_fingerprint,product_id,sku_id,first_job_id,last_job_id,source_product_fingerprint,original_source_product_key)
VALUES ($1,$2,$3,$4,$5,$6,$7,$7,$8,$9)
ON CONFLICT (source_namespace,source_product_key,source_sku_key) DO UPDATE
SET source_fingerprint = EXCLUDED.source_fingerprint, source_product_fingerprint = EXCLUDED.source_product_fingerprint, last_job_id = EXCLUDED.last_job_id, updated_at = now()
`

type UpsertProductImportSourceRefParams struct {
	SourceNamespace          string      `db:"source_namespace" json:"source_namespace"`
	SourceProductKey         string      `db:"source_product_key" json:"source_product_key"`
	SourceSkuKey             string      `db:"source_sku_key" json:"source_sku_key"`
	SourceFingerprint        string      `db:"source_fingerprint" json:"source_fingerprint"`
	ProductID                uuid.UUID   `db:"product_id" json:"product_id"`
	SkuID                    pgtype.UUID `db:"sku_id" json:"sku_id"`
	FirstJobID               uuid.UUID   `db:"first_job_id" json:"first_job_id"`
	SourceProductFingerprint string      `db:"source_product_fingerprint" json:"source_product_fingerprint"`
	OriginalSourceProductKey string      `db:"original_source_product_key" json:"original_source_product_key"`
}

func (q *Queries) UpsertProductImportSourceRef(ctx context.Context, arg UpsertProductImportSourceRefParams) error {
	_, err := q.db.Exec(ctx, upsertProductImportSourceRef,
		arg.SourceNamespace,
		arg.SourceProductKey,
		arg.SourceSkuKey,
		arg.SourceFingerprint,
		arg.ProductID,
		arg.SkuID,
		arg.FirstJobID,
		arg.SourceProductFingerprint,
		arg.OriginalSourceProductKey,
	)
	return err
}
