// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_import_jobs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingProductImportJob = `-- name: ClaimNextPendingProductImportJob :one
WITH picked AS (
    SELECT pj.job_id
    FROM product_import_jobs pj
    JOIN import_jobs ij ON ij.id = pj.job_id
    WHERE ij.type = 'PRODUCT_IMPORT'
      AND ij.status = 'PENDING'
    ORDER BY ij.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), updated AS (
    UPDATE import_jobs ij
    SET status = 'RUNNING',
        progress = 1,
        updated_at = now()
    FROM picked
    WHERE ij.id = picked.job_id
    RETURNING ij.id, ij.type, ij.status, ij.progress, ij.result_file_url, ij.error_report_url, ij.created_by_user_id, ij.created_at, ij.updated_at
)
SELECT
    updated.id,
    updated.type,
    updated.status,
    updated.progress,
    updated.result_file_url,
    updated.error_report_url,
    updated.created_by_user_id,
    updated.created_at,
    updated.updated_at,
    pj.job_id,
    pj.excel_file_path,
    pj.excel_file_name,
    pj.images_zip_path,
    pj.images_zip_name,
    pj.image_base_url,
    pj.total_rows,
    pj.success_rows,
    pj.failed_rows,
    pj.created_at AS product_import_created_at,
    pj.updated_at AS product_import_updated_at
FROM updated
JOIN product_import_jobs pj ON pj.job_id = updated.id
`

type ClaimNextPendingProductImportJobRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	Type                   string             `db:"type" json:"type"`
	Status                 string             `db:"status" json:"status"`
	Progress               int32              `db:"progress" json:"progress"`
	ResultFileUrl          *string            `db:"result_file_url" json:"result_file_url"`
	ErrorReportUrl         *string            `db:"error_report_url" json:"error_report_url"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JobID                  uuid.UUID          `db:"job_id" json:"job_id"`
	ExcelFilePath          string             `db:"excel_file_path" json:"excel_file_path"`
	ExcelFileName          string             `db:"excel_file_name" json:"excel_file_name"`
	ImagesZipPath          *string            `db:"images_zip_path" json:"images_zip_path"`
	ImagesZipName          *string            `db:"images_zip_name" json:"images_zip_name"`
	ImageBaseUrl           *string            `db:"image_base_url" json:"image_base_url"`
	TotalRows              int32              `db:"total_rows" json:"total_rows"`
	SuccessRows            int32              `db:"success_rows" json:"success_rows"`
	FailedRows             int32              `db:"failed_rows" json:"failed_rows"`
	ProductImportCreatedAt pgtype.Timestamptz `db:"product_import_created_at" json:"product_import_created_at"`
	ProductImportUpdatedAt pgtype.Timestamptz `db:"product_import_updated_at" json:"product_import_updated_at"`
}

func (q *Queries) ClaimNextPendingProductImportJob(ctx context.Context) (ClaimNextPendingProductImportJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextPendingProductImportJob)
	var i ClaimNextPendingProductImportJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.ResultFileUrl,
		&i.ErrorReportUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.ProductImportCreatedAt,
		&i.ProductImportUpdatedAt,
	)
	return i, err
}

const createProductImportJob = `-- name: CreateProductImportJob :one
INSERT INTO product_import_jobs (
    job_id,
    excel_file_path,
    excel_file_name,
    images_zip_path,
    images_zip_name,
    image_base_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING job_id, excel_file_path, excel_file_name, images_zip_path, images_zip_name, image_base_url, total_rows, success_rows, failed_rows, created_at, updated_at
`

type CreateProductImportJobParams struct {
	JobID         uuid.UUID `db:"job_id" json:"job_id"`
	ExcelFilePath string    `db:"excel_file_path" json:"excel_file_path"`
	ExcelFileName string    `db:"excel_file_name" json:"excel_file_name"`
	ImagesZipPath *string   `db:"images_zip_path" json:"images_zip_path"`
	ImagesZipName *string   `db:"images_zip_name" json:"images_zip_name"`
	ImageBaseUrl  *string   `db:"image_base_url" json:"image_base_url"`
}

func (q *Queries) CreateProductImportJob(ctx context.Context, arg CreateProductImportJobParams) (ProductImportJob, error) {
	row := q.db.QueryRow(ctx, createProductImportJob,
		arg.JobID,
		arg.ExcelFilePath,
		arg.ExcelFileName,
		arg.ImagesZipPath,
		arg.ImagesZipName,
		arg.ImageBaseUrl,
	)
	var i ProductImportJob
	err := row.Scan(
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductImportRow = `-- name: CreateProductImportRow :one
INSERT INTO product_import_rows (
    job_id,
    line_no,
    group_key,
    sku_code,
    product_name,
    row_data,
    status,
    error_message,
    product_id,
    sku_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, job_id, line_no, group_key, sku_code, product_name, row_data, status, error_message, product_id, sku_id, created_at, updated_at
`

type CreateProductImportRowParams struct {
	JobID        uuid.UUID       `db:"job_id" json:"job_id"`
	LineNo       int32           `db:"line_no" json:"line_no"`
	GroupKey     *string         `db:"group_key" json:"group_key"`
	SkuCode      *string         `db:"sku_code" json:"sku_code"`
	ProductName  *string         `db:"product_name" json:"product_name"`
	RowData      json.RawMessage `db:"row_data" json:"row_data"`
	Status       string          `db:"status" json:"status"`
	ErrorMessage *string         `db:"error_message" json:"error_message"`
	ProductID    pgtype.UUID     `db:"product_id" json:"product_id"`
	SkuID        pgtype.UUID     `db:"sku_id" json:"sku_id"`
}

func (q *Queries) CreateProductImportRow(ctx context.Context, arg CreateProductImportRowParams) (ProductImportRow, error) {
	row := q.db.QueryRow(ctx, createProductImportRow,
		arg.JobID,
		arg.LineNo,
		arg.GroupKey,
		arg.SkuCode,
		arg.ProductName,
		arg.RowData,
		arg.Status,
		arg.ErrorMessage,
		arg.ProductID,
		arg.SkuID,
	)
	var i ProductImportRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.LineNo,
		&i.GroupKey,
		&i.SkuCode,
		&i.ProductName,
		&i.RowData,
		&i.Status,
		&i.ErrorMessage,
		&i.ProductID,
		&i.SkuID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductImportJob = `-- name: GetProductImportJob :one
SELECT job_id, excel_file_path, excel_file_name, images_zip_path, images_zip_name, image_base_url, total_rows, success_rows, failed_rows, created_at, updated_at
FROM product_import_jobs
WHERE job_id = $1
`

func (q *Queries) GetProductImportJob(ctx context.Context, jobID uuid.UUID) (ProductImportJob, error) {
	row := q.db.QueryRow(ctx, getProductImportJob, jobID)
	var i ProductImportJob
	err := row.Scan(
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductImportRowsByJob = `-- name: ListProductImportRowsByJob :many
SELECT id, job_id, line_no, group_key, sku_code, product_name, row_data, status, error_message, product_id, sku_id, created_at, updated_at
FROM product_import_rows
WHERE job_id = $1
ORDER BY line_no ASC
`

func (q *Queries) ListProductImportRowsByJob(ctx context.Context, jobID uuid.UUID) ([]ProductImportRow, error) {
	rows, err := q.db.Query(ctx, listProductImportRowsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImportRow
	for rows.Next() {
		var i ProductImportRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.LineNo,
			&i.GroupKey,
			&i.SkuCode,
			&i.ProductName,
			&i.RowData,
			&i.Status,
			&i.ErrorMessage,
			&i.ProductID,
			&i.SkuID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetRunningProductImportJobs = `-- name: ResetRunningProductImportJobs :execrows
UPDATE import_jobs
SET status = 'PENDING',
    progress = 0,
    updated_at = now()
WHERE type = 'PRODUCT_IMPORT'
  AND status = 'RUNNING'
`

func (q *Queries) ResetRunningProductImportJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetRunningProductImportJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProductImportJobCounts = `-- name: UpdateProductImportJobCounts :one
UPDATE product_import_jobs
SET total_rows = $2,
    success_rows = $3,
    failed_rows = $4,
    updated_at = now()
WHERE job_id = $1
RETURNING job_id, excel_file_path, excel_file_name, images_zip_path, images_zip_name, image_base_url, total_rows, success_rows, failed_rows, created_at, updated_at
`

type UpdateProductImportJobCountsParams struct {
	JobID       uuid.UUID `db:"job_id" json:"job_id"`
	TotalRows   int32     `db:"total_rows" json:"total_rows"`
	SuccessRows int32     `db:"success_rows" json:"success_rows"`
	FailedRows  int32     `db:"failed_rows" json:"failed_rows"`
}

func (q *Queries) UpdateProductImportJobCounts(ctx context.Context, arg UpdateProductImportJobCountsParams) (ProductImportJob, error) {
	row := q.db.QueryRow(ctx, updateProductImportJobCounts,
		arg.JobID,
		arg.TotalRows,
		arg.SuccessRows,
		arg.FailedRows,
	)
	var i ProductImportJob
	err := row.Scan(
		&i.JobID,
		&i.ExcelFilePath,
		&i.ExcelFileName,
		&i.ImagesZipPath,
		&i.ImagesZipName,
		&i.ImageBaseUrl,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductImportRowResult = `-- name: UpdateProductImportRowResult :one
UPDATE product_import_rows
SET status = $2,
    error_message = $3,
    product_id = $4,
    sku_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, job_id, line_no, group_key, sku_code, product_name, row_data, status, error_message, product_id, sku_id, created_at, updated_at
`

type UpdateProductImportRowResultParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Status       string      `db:"status" json:"status"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ProductID    pgtype.UUID `db:"product_id" json:"product_id"`
	SkuID        pgtype.UUID `db:"sku_id" json:"sku_id"`
}

func (q *Queries) UpdateProductImportRowResult(ctx context.Context, arg UpdateProductImportRowResultParams) (ProductImportRow, error) {
	row := q.db.QueryRow(ctx, updateProductImportRowResult,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.ProductID,
		arg.SkuID,
	)
	var i ProductImportRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.LineNo,
		&i.GroupKey,
		&i.SkuCode,
		&i.ProductName,
		&i.RowData,
		&i.Status,
		&i.ErrorMessage,
		&i.ProductID,
		&i.SkuID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
