// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_export_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingProductExportJob = `-- name: ClaimNextPendingProductExportJob :one
WITH picked AS (
    SELECT pej.job_id
    FROM product_export_jobs pej
    JOIN import_jobs ij ON ij.id = pej.job_id
    WHERE ij.type = 'PRODUCT_EXPORT'
      AND ij.status = 'PENDING'
    ORDER BY ij.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), updated AS (
    UPDATE import_jobs ij
    SET status = 'RUNNING',
        progress = 1,
        updated_at = now()
    FROM picked
    WHERE ij.id = picked.job_id
    RETURNING ij.id, ij.type, ij.status, ij.progress, ij.result_file_url, ij.error_report_url, ij.created_by_user_id, ij.created_at, ij.updated_at
)
SELECT
    updated.id,
    updated.type,
    updated.status,
    updated.progress,
    updated.result_file_url,
    updated.error_report_url,
    updated.created_by_user_id,
    updated.created_at,
    updated.updated_at,
    pej.job_id,
    pej.query,
    pej.category_id,
    pej.product_status,
    pej.needs_review,
    pej.exported_rows,
    pej.created_at AS export_created_at,
    pej.updated_at AS export_updated_at
FROM updated
JOIN product_export_jobs pej ON pej.job_id = updated.id
`

type ClaimNextPendingProductExportJobRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Type            string             `db:"type" json:"type"`
	Status          string             `db:"status" json:"status"`
	Progress        int32              `db:"progress" json:"progress"`
	ResultFileUrl   *string            `db:"result_file_url" json:"result_file_url"`
	ErrorReportUrl  *string            `db:"error_report_url" json:"error_report_url"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	Query           *string            `db:"query" json:"query"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	ProductStatus   *string            `db:"product_status" json:"product_status"`
	NeedsReview     bool               `db:"needs_review" json:"needs_review"`
	ExportedRows    int32              `db:"exported_rows" json:"exported_rows"`
	ExportCreatedAt pgtype.Timestamptz `db:"export_created_at" json:"export_created_at"`
	ExportUpdatedAt pgtype.Timestamptz `db:"export_updated_at" json:"export_updated_at"`
}

func (q *Queries) ClaimNextPendingProductExportJob(ctx context.Context) (ClaimNextPendingProductExportJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextPendingProductExportJob)
	var i ClaimNextPendingProductExportJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.ResultFileUrl,
		&i.ErrorReportUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JobID,
		&i.Query,
		&i.CategoryID,
		&i.ProductStatus,
		&i.NeedsReview,
		&i.ExportedRows,
		&i.ExportCreatedAt,
		&i.ExportUpdatedAt,
	)
	return i, err
}

const createProductExportJob = `-- name: CreateProductExportJob :one
INSERT INTO product_export_jobs (
    job_id,
    query,
    category_id,
    product_status,
    needs_review
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING job_id, query, category_id, product_status, needs_review, exported_rows, created_at, updated_at
`

type CreateProductExportJobParams struct {
	JobID         uuid.UUID   `db:"job_id" json:"job_id"`
	Query         *string     `db:"query" json:"query"`
	CategoryID    pgtype.UUID `db:"category_id" json:"category_id"`
	ProductStatus *string     `db:"product_status" json:"product_status"`
	NeedsReview   bool        `db:"needs_review" json:"needs_review"`
}

type CreateProductExportJobRow struct {
	JobID         uuid.UUID          `db:"job_id" json:"job_id"`
	Query         *string            `db:"query" json:"query"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	ProductStatus *string            `db:"product_status" json:"product_status"`
	NeedsReview   bool               `db:"needs_review" json:"needs_review"`
	ExportedRows  int32              `db:"exported_rows" json:"exported_rows"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProductExportJob(ctx context.Context, arg CreateProductExportJobParams) (CreateProductExportJobRow, error) {
	row := q.db.QueryRow(ctx, createProductExportJob,
		arg.JobID,
		arg.Query,
		arg.CategoryID,
		arg.ProductStatus,
		arg.NeedsReview,
	)
	var i CreateProductExportJobRow
	err := row.Scan(
		&i.JobID,
		&i.Query,
		&i.CategoryID,
		&i.ProductStatus,
		&i.NeedsReview,
		&i.ExportedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductExportJob = `-- name: GetProductExportJob :one
SELECT job_id, query, category_id, product_status, needs_review, exported_rows, created_at, updated_at
FROM product_export_jobs
WHERE job_id = $1
`

type GetProductExportJobRow struct {
	JobID         uuid.UUID          `db:"job_id" json:"job_id"`
	Query         *string            `db:"query" json:"query"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	ProductStatus *string            `db:"product_status" json:"product_status"`
	NeedsReview   bool               `db:"needs_review" json:"needs_review"`
	ExportedRows  int32              `db:"exported_rows" json:"exported_rows"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetProductExportJob(ctx context.Context, jobID uuid.UUID) (GetProductExportJobRow, error) {
	row := q.db.QueryRow(ctx, getProductExportJob, jobID)
	var i GetProductExportJobRow
	err := row.Scan(
		&i.JobID,
		&i.Query,
		&i.CategoryID,
		&i.ProductStatus,
		&i.NeedsReview,
		&i.ExportedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductExportProducts = `-- name: ListProductExportProducts :many
SELECT p.id, p.name, p.description, p.category_id, p.cover_image_url, p.images, p.tags, p.filter_dimensions, p.created_at, p.updated_at, p.status
FROM catalog_products p
WHERE (
    $1::text IS NULL
    OR position(lower(btrim($1::text)) in lower(p.name)) > 0
    OR position(lower(btrim($1::text)) in lower(p.id::text)) > 0
    OR position(lower(btrim($1::text)) in lower(coalesce((SELECT c.name FROM catalog_categories c WHERE c.id = p.category_id), '无'))) > 0
    OR EXISTS (
        SELECT 1 FROM catalog_skus s
        WHERE s.product_id = p.id
          AND position(lower(btrim($1::text)) in lower(s.name || ' ' || coalesce(s.sku_code, ''))) > 0
    )
)
  AND ($2::uuid IS NULL OR p.category_id = $2)
  AND ($3::text IS NULL OR p.status = $3)
  AND (NOT $4::boolean OR EXISTS (
      SELECT 1 FROM product_import_reviews r WHERE r.product_id = p.id AND r.status = 'PENDING'
  ))
ORDER BY CASE p.status WHEN 'ACTIVE' THEN 0 WHEN 'DRAFT' THEN 1 WHEN 'INACTIVE' THEN 2 ELSE 3 END,
         p.created_at DESC, p.id ASC
LIMIT $6 OFFSET $5
`

type ListProductExportProductsParams struct {
	Q           *string     `db:"q" json:"q"`
	CategoryID  pgtype.UUID `db:"category_id" json:"category_id"`
	Status      *string     `db:"status" json:"status"`
	NeedsReview bool        `db:"needs_review" json:"needs_review"`
	Offset      int32       `db:"offset" json:"offset"`
	Limit       int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListProductExportProducts(ctx context.Context, arg ListProductExportProductsParams) ([]CatalogProduct, error) {
	rows, err := q.db.Query(ctx, listProductExportProducts,
		arg.Q,
		arg.CategoryID,
		arg.Status,
		arg.NeedsReview,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogProduct
	for rows.Next() {
		var i CatalogProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.CoverImageUrl,
			&i.Images,
			&i.Tags,
			&i.FilterDimensions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetRunningProductExportJobs = `-- name: ResetRunningProductExportJobs :execrows
UPDATE import_jobs
SET status = 'PENDING',
    progress = 0,
    updated_at = now()
WHERE type = 'PRODUCT_EXPORT'
  AND status = 'RUNNING'
`

func (q *Queries) ResetRunningProductExportJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetRunningProductExportJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProductExportJobRows = `-- name: UpdateProductExportJobRows :one
UPDATE product_export_jobs
SET exported_rows = $2,
    updated_at = now()
WHERE job_id = $1
RETURNING job_id, query, category_id, product_status, needs_review, exported_rows, created_at, updated_at
`

type UpdateProductExportJobRowsParams struct {
	JobID        uuid.UUID `db:"job_id" json:"job_id"`
	ExportedRows int32     `db:"exported_rows" json:"exported_rows"`
}

type UpdateProductExportJobRowsRow struct {
	JobID         uuid.UUID          `db:"job_id" json:"job_id"`
	Query         *string            `db:"query" json:"query"`
	CategoryID    pgtype.UUID        `db:"category_id" json:"category_id"`
	ProductStatus *string            `db:"product_status" json:"product_status"`
	NeedsReview   bool               `db:"needs_review" json:"needs_review"`
	ExportedRows  int32              `db:"exported_rows" json:"exported_rows"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateProductExportJobRows(ctx context.Context, arg UpdateProductExportJobRowsParams) (UpdateProductExportJobRowsRow, error) {
	row := q.db.QueryRow(ctx, updateProductExportJobRows, arg.JobID, arg.ExportedRows)
	var i UpdateProductExportJobRowsRow
	err := row.Scan(
		&i.JobID,
		&i.Query,
		&i.CategoryID,
		&i.ProductStatus,
		&i.NeedsReview,
		&i.ExportedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
