// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_request_export_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingProductRequestExportJob = `-- name: ClaimNextPendingProductRequestExportJob :one
WITH picked AS (
    SELECT pej.job_id
    FROM product_request_export_jobs pej
    JOIN import_jobs ij ON ij.id = pej.job_id
    WHERE ij.type = 'PRODUCT_REQUEST_EXPORT'
      AND ij.status = 'PENDING'
    ORDER BY ij.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
), updated AS (
    UPDATE import_jobs ij
    SET status = 'RUNNING',
        progress = 1,
        updated_at = now()
    FROM picked
    WHERE ij.id = picked.job_id
    RETURNING ij.id, ij.type, ij.status, ij.progress, ij.result_file_url, ij.error_report_url, ij.created_by_user_id, ij.created_at, ij.updated_at
)
SELECT
    updated.id,
    updated.type,
    updated.status,
    updated.progress,
    updated.result_file_url,
    updated.error_report_url,
    updated.created_by_user_id,
    updated.created_at,
    updated.updated_at,
    pej.job_id,
    pej.created_after,
    pej.created_before,
    pej.exported_rows,
    pej.created_at AS export_created_at,
    pej.updated_at AS export_updated_at
FROM updated
JOIN product_request_export_jobs pej ON pej.job_id = updated.id
`

type ClaimNextPendingProductRequestExportJobRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Type            string             `db:"type" json:"type"`
	Status          string             `db:"status" json:"status"`
	Progress        int32              `db:"progress" json:"progress"`
	ResultFileUrl   *string            `db:"result_file_url" json:"result_file_url"`
	ErrorReportUrl  *string            `db:"error_report_url" json:"error_report_url"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	CreatedAfter    pgtype.Timestamptz `db:"created_after" json:"created_after"`
	CreatedBefore   pgtype.Timestamptz `db:"created_before" json:"created_before"`
	ExportedRows    int32              `db:"exported_rows" json:"exported_rows"`
	ExportCreatedAt pgtype.Timestamptz `db:"export_created_at" json:"export_created_at"`
	ExportUpdatedAt pgtype.Timestamptz `db:"export_updated_at" json:"export_updated_at"`
}

func (q *Queries) ClaimNextPendingProductRequestExportJob(ctx context.Context) (ClaimNextPendingProductRequestExportJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextPendingProductRequestExportJob)
	var i ClaimNextPendingProductRequestExportJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.ResultFileUrl,
		&i.ErrorReportUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JobID,
		&i.CreatedAfter,
		&i.CreatedBefore,
		&i.ExportedRows,
		&i.ExportCreatedAt,
		&i.ExportUpdatedAt,
	)
	return i, err
}

const createProductRequestExportJob = `-- name: CreateProductRequestExportJob :one
INSERT INTO product_request_export_jobs (
    job_id,
    created_after,
    created_before
) VALUES (
    $1,
    $2,
    $3
)
RETURNING job_id, created_after, created_before, exported_rows, created_at, updated_at
`

type CreateProductRequestExportJobParams struct {
	JobID         uuid.UUID          `db:"job_id" json:"job_id"`
	CreatedAfter  pgtype.Timestamptz `db:"created_after" json:"created_after"`
	CreatedBefore pgtype.Timestamptz `db:"created_before" json:"created_before"`
}

func (q *Queries) CreateProductRequestExportJob(ctx context.Context, arg CreateProductRequestExportJobParams) (ProductRequestExportJob, error) {
	row := q.db.QueryRow(ctx, createProductRequestExportJob, arg.JobID, arg.CreatedAfter, arg.CreatedBefore)
	var i ProductRequestExportJob
	err := row.Scan(
		&i.JobID,
		&i.CreatedAfter,
		&i.CreatedBefore,
		&i.ExportedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductRequestExportJob = `-- name: GetProductRequestExportJob :one
SELECT job_id, created_after, created_before, exported_rows, created_at, updated_at
FROM product_request_export_jobs
WHERE job_id = $1
`

func (q *Queries) GetProductRequestExportJob(ctx context.Context, jobID uuid.UUID) (ProductRequestExportJob, error) {
	row := q.db.QueryRow(ctx, getProductRequestExportJob, jobID)
	var i ProductRequestExportJob
	err := row.Scan(
		&i.JobID,
		&i.CreatedAfter,
		&i.CreatedBefore,
		&i.ExportedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetRunningProductRequestExportJobs = `-- name: ResetRunningProductRequestExportJobs :execrows
UPDATE import_jobs
SET status = 'PENDING',
    progress = 0,
    updated_at = now()
WHERE type = 'PRODUCT_REQUEST_EXPORT'
  AND status = 'RUNNING'
`

func (q *Queries) ResetRunningProductRequestExportJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetRunningProductRequestExportJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProductRequestExportJobRows = `-- name: UpdateProductRequestExportJobRows :one
UPDATE product_request_export_jobs
SET exported_rows = $2,
    updated_at = now()
WHERE job_id = $1
RETURNING job_id, created_after, created_before, exported_rows, created_at, updated_at
`

type UpdateProductRequestExportJobRowsParams struct {
	JobID        uuid.UUID `db:"job_id" json:"job_id"`
	ExportedRows int32     `db:"exported_rows" json:"exported_rows"`
}

func (q *Queries) UpdateProductRequestExportJobRows(ctx context.Context, arg UpdateProductRequestExportJobRowsParams) (ProductRequestExportJob, error) {
	row := q.db.QueryRow(ctx, updateProductRequestExportJobRows, arg.JobID, arg.ExportedRows)
	var i ProductRequestExportJob
	err := row.Scan(
		&i.JobID,
		&i.CreatedAfter,
		&i.CreatedBefore,
		&i.ExportedRows,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
