// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: support.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimSupportConversation = `-- name: ClaimSupportConversation :one
UPDATE support_conversations
SET assignee_user_id = $2,
    assignee_role = $3,
    status = 'OPEN_ASSIGNED',
    updated_at = now()
WHERE id = $1
  AND closed_at IS NULL
  AND (assignee_user_id IS NULL OR assignee_user_id = $2)
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

type ClaimSupportConversationParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	AssigneeUserID pgtype.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole   *string     `db:"assignee_role" json:"assignee_role"`
}

func (q *Queries) ClaimSupportConversation(ctx context.Context, arg ClaimSupportConversationParams) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, claimSupportConversation, arg.ID, arg.AssigneeUserID, arg.AssigneeRole)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const countSupportConversations = `-- name: CountSupportConversations :one
SELECT count(*)
FROM support_conversations
WHERE ($1::uuid IS NULL OR assignee_user_id = $1)
  AND (
    NOT $2::boolean
    OR (assignee_user_id IS NULL AND status = 'OPEN_UNASSIGNED')
  )
  AND (
    NOT $3::boolean
    OR staff_unread_count > 0
  )
  AND (
    $4::uuid IS NULL
    OR customer_user_id = $4
  )
  AND (
    $5::uuid IS NULL
    OR owner_sales_user_id = $5
  )
  AND (
    $6::text IS NULL
    OR status = $6
  )
`

type CountSupportConversationsParams struct {
	AssigneeUserID   pgtype.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	UnassignedOnly   bool        `db:"unassigned_only" json:"unassigned_only"`
	UnreadOnly       bool        `db:"unread_only" json:"unread_only"`
	CustomerUserID   pgtype.UUID `db:"customer_user_id" json:"customer_user_id"`
	OwnerSalesUserID pgtype.UUID `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Status           *string     `db:"status" json:"status"`
}

func (q *Queries) CountSupportConversations(ctx context.Context, arg CountSupportConversationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSupportConversations,
		arg.AssigneeUserID,
		arg.UnassignedOnly,
		arg.UnreadOnly,
		arg.CustomerUserID,
		arg.OwnerSalesUserID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupportMessages = `-- name: CountSupportMessages :one
SELECT count(*)
FROM support_messages
WHERE conversation_id = $1
`

func (q *Queries) CountSupportMessages(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSupportMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupportConversation = `-- name: CreateSupportConversation :one
INSERT INTO support_conversations (
    customer_user_id,
    owner_sales_user_id,
    assignee_user_id,
    assignee_role,
    status,
    last_message_type,
    last_message_preview,
    last_message_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    COALESCE($8, now())
)
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

type CreateSupportConversationParams struct {
	CustomerUserID     uuid.UUID   `db:"customer_user_id" json:"customer_user_id"`
	OwnerSalesUserID   pgtype.UUID `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	AssigneeUserID     pgtype.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole       *string     `db:"assignee_role" json:"assignee_role"`
	Status             string      `db:"status" json:"status"`
	LastMessageType    *string     `db:"last_message_type" json:"last_message_type"`
	LastMessagePreview *string     `db:"last_message_preview" json:"last_message_preview"`
	Column8            interface{} `db:"column_8" json:"column_8"`
}

func (q *Queries) CreateSupportConversation(ctx context.Context, arg CreateSupportConversationParams) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, createSupportConversation,
		arg.CustomerUserID,
		arg.OwnerSalesUserID,
		arg.AssigneeUserID,
		arg.AssigneeRole,
		arg.Status,
		arg.LastMessageType,
		arg.LastMessagePreview,
		arg.Column8,
	)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createSupportConversationTransfer = `-- name: CreateSupportConversationTransfer :one
INSERT INTO support_conversation_transfers (
    conversation_id,
    from_user_id,
    from_role,
    to_user_id,
    to_role,
    note,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, conversation_id, from_user_id, from_role, to_user_id, to_role, note, created_by_user_id, created_at
`

type CreateSupportConversationTransferParams struct {
	ConversationID  uuid.UUID   `db:"conversation_id" json:"conversation_id"`
	FromUserID      pgtype.UUID `db:"from_user_id" json:"from_user_id"`
	FromRole        *string     `db:"from_role" json:"from_role"`
	ToUserID        uuid.UUID   `db:"to_user_id" json:"to_user_id"`
	ToRole          string      `db:"to_role" json:"to_role"`
	Note            *string     `db:"note" json:"note"`
	CreatedByUserID uuid.UUID   `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) CreateSupportConversationTransfer(ctx context.Context, arg CreateSupportConversationTransferParams) (SupportConversationTransfer, error) {
	row := q.db.QueryRow(ctx, createSupportConversationTransfer,
		arg.ConversationID,
		arg.FromUserID,
		arg.FromRole,
		arg.ToUserID,
		arg.ToRole,
		arg.Note,
		arg.CreatedByUserID,
	)
	var i SupportConversationTransfer
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.FromUserID,
		&i.FromRole,
		&i.ToUserID,
		&i.ToRole,
		&i.Note,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createSupportMessage = `-- name: CreateSupportMessage :one
INSERT INTO support_messages (
    conversation_id,
    sender_type,
    sender_user_id,
    sender_role,
    message_type,
    text_content,
    asset_id,
    card_payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, conversation_id, sender_type, sender_user_id, sender_role, message_type, text_content, asset_id, card_payload, created_at
`

type CreateSupportMessageParams struct {
	ConversationID uuid.UUID   `db:"conversation_id" json:"conversation_id"`
	SenderType     string      `db:"sender_type" json:"sender_type"`
	SenderUserID   pgtype.UUID `db:"sender_user_id" json:"sender_user_id"`
	SenderRole     *string     `db:"sender_role" json:"sender_role"`
	MessageType    string      `db:"message_type" json:"message_type"`
	TextContent    *string     `db:"text_content" json:"text_content"`
	AssetID        pgtype.UUID `db:"asset_id" json:"asset_id"`
	CardPayload    []byte      `db:"card_payload" json:"card_payload"`
}

func (q *Queries) CreateSupportMessage(ctx context.Context, arg CreateSupportMessageParams) (SupportMessage, error) {
	row := q.db.QueryRow(ctx, createSupportMessage,
		arg.ConversationID,
		arg.SenderType,
		arg.SenderUserID,
		arg.SenderRole,
		arg.MessageType,
		arg.TextContent,
		arg.AssetID,
		arg.CardPayload,
	)
	var i SupportMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderType,
		&i.SenderUserID,
		&i.SenderRole,
		&i.MessageType,
		&i.TextContent,
		&i.AssetID,
		&i.CardPayload,
		&i.CreatedAt,
	)
	return i, err
}

const createSupportMessageAsset = `-- name: CreateSupportMessageAsset :one
INSERT INTO support_message_assets (
    conversation_id,
    uploaded_by_user_id,
    content_type,
    file_name,
    file_size,
    url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, conversation_id, uploaded_by_user_id, content_type, file_name, file_size, url, created_at
`

type CreateSupportMessageAssetParams struct {
	ConversationID   uuid.UUID `db:"conversation_id" json:"conversation_id"`
	UploadedByUserID uuid.UUID `db:"uploaded_by_user_id" json:"uploaded_by_user_id"`
	ContentType      string    `db:"content_type" json:"content_type"`
	FileName         string    `db:"file_name" json:"file_name"`
	FileSize         int64     `db:"file_size" json:"file_size"`
	Url              string    `db:"url" json:"url"`
}

func (q *Queries) CreateSupportMessageAsset(ctx context.Context, arg CreateSupportMessageAssetParams) (SupportMessageAsset, error) {
	row := q.db.QueryRow(ctx, createSupportMessageAsset,
		arg.ConversationID,
		arg.UploadedByUserID,
		arg.ContentType,
		arg.FileName,
		arg.FileSize,
		arg.Url,
	)
	var i SupportMessageAsset
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UploadedByUserID,
		&i.ContentType,
		&i.FileName,
		&i.FileSize,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSupportConversationByCustomer = `-- name: GetActiveSupportConversationByCustomer :one
SELECT id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
FROM support_conversations
WHERE customer_user_id = $1
  AND closed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSupportConversationByCustomer(ctx context.Context, customerUserID uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, getActiveSupportConversationByCustomer, customerUserID)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSupportConversation = `-- name: GetSupportConversation :one
SELECT id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
FROM support_conversations
WHERE id = $1
`

func (q *Queries) GetSupportConversation(ctx context.Context, id uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, getSupportConversation, id)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSupportMessageAsset = `-- name: GetSupportMessageAsset :one
SELECT id, conversation_id, uploaded_by_user_id, content_type, file_name, file_size, url, created_at
FROM support_message_assets
WHERE id = $1
`

func (q *Queries) GetSupportMessageAsset(ctx context.Context, id uuid.UUID) (SupportMessageAsset, error) {
	row := q.db.QueryRow(ctx, getSupportMessageAsset, id)
	var i SupportMessageAsset
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UploadedByUserID,
		&i.ContentType,
		&i.FileName,
		&i.FileSize,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const listSupportConversations = `-- name: ListSupportConversations :many
SELECT id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
FROM support_conversations
WHERE ($1::uuid IS NULL OR assignee_user_id = $1)
  AND (
    NOT $2::boolean
    OR (assignee_user_id IS NULL AND status = 'OPEN_UNASSIGNED')
  )
  AND (
    NOT $3::boolean
    OR staff_unread_count > 0
  )
  AND (
    $4::uuid IS NULL
    OR customer_user_id = $4
  )
  AND (
    $5::uuid IS NULL
    OR owner_sales_user_id = $5
  )
  AND (
    $6::text IS NULL
    OR status = $6
  )
ORDER BY last_message_at DESC, created_at DESC
LIMIT $8 OFFSET $7
`

type ListSupportConversationsParams struct {
	AssigneeUserID   pgtype.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	UnassignedOnly   bool        `db:"unassigned_only" json:"unassigned_only"`
	UnreadOnly       bool        `db:"unread_only" json:"unread_only"`
	CustomerUserID   pgtype.UUID `db:"customer_user_id" json:"customer_user_id"`
	OwnerSalesUserID pgtype.UUID `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	Status           *string     `db:"status" json:"status"`
	Offset           int32       `db:"offset" json:"offset"`
	Limit            int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListSupportConversations(ctx context.Context, arg ListSupportConversationsParams) ([]SupportConversation, error) {
	rows, err := q.db.Query(ctx, listSupportConversations,
		arg.AssigneeUserID,
		arg.UnassignedOnly,
		arg.UnreadOnly,
		arg.CustomerUserID,
		arg.OwnerSalesUserID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportConversation
	for rows.Next() {
		var i SupportConversation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerUserID,
			&i.OwnerSalesUserID,
			&i.AssigneeUserID,
			&i.AssigneeRole,
			&i.Status,
			&i.LastMessageType,
			&i.LastMessagePreview,
			&i.LastMessageAt,
			&i.CustomerUnreadCount,
			&i.StaffUnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportMessages = `-- name: ListSupportMessages :many
SELECT id, conversation_id, sender_type, sender_user_id, sender_role, message_type, text_content, asset_id, card_payload, created_at
FROM support_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type ListSupportMessagesParams struct {
	ConversationID uuid.UUID `db:"conversation_id" json:"conversation_id"`
	Offset         int32     `db:"offset" json:"offset"`
	Limit          int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListSupportMessages(ctx context.Context, arg ListSupportMessagesParams) ([]SupportMessage, error) {
	rows, err := q.db.Query(ctx, listSupportMessages, arg.ConversationID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportMessage
	for rows.Next() {
		var i SupportMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderType,
			&i.SenderUserID,
			&i.SenderRole,
			&i.MessageType,
			&i.TextContent,
			&i.AssetID,
			&i.CardPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSupportConversationReadForCustomer = `-- name: MarkSupportConversationReadForCustomer :one
UPDATE support_conversations
SET customer_unread_count = 0,
    updated_at = now()
WHERE id = $1
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

func (q *Queries) MarkSupportConversationReadForCustomer(ctx context.Context, id uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, markSupportConversationReadForCustomer, id)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const markSupportConversationReadForStaff = `-- name: MarkSupportConversationReadForStaff :one
UPDATE support_conversations
SET staff_unread_count = 0,
    updated_at = now()
WHERE id = $1
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

func (q *Queries) MarkSupportConversationReadForStaff(ctx context.Context, id uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, markSupportConversationReadForStaff, id)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const releaseSupportConversation = `-- name: ReleaseSupportConversation :one
UPDATE support_conversations
SET assignee_user_id = NULL,
    assignee_role = NULL,
    status = 'OPEN_UNASSIGNED',
    updated_at = now()
WHERE id = $1
  AND closed_at IS NULL
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

func (q *Queries) ReleaseSupportConversation(ctx context.Context, id uuid.UUID) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, releaseSupportConversation, id)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const transferSupportConversation = `-- name: TransferSupportConversation :one
UPDATE support_conversations
SET assignee_user_id = $2,
    assignee_role = $3,
    status = 'OPEN_ASSIGNED',
    updated_at = now()
WHERE id = $1
  AND closed_at IS NULL
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

type TransferSupportConversationParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	AssigneeUserID pgtype.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	AssigneeRole   *string     `db:"assignee_role" json:"assignee_role"`
}

func (q *Queries) TransferSupportConversation(ctx context.Context, arg TransferSupportConversationParams) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, transferSupportConversation, arg.ID, arg.AssigneeUserID, arg.AssigneeRole)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateSupportConversationAfterMessage = `-- name: UpdateSupportConversationAfterMessage :one
UPDATE support_conversations
SET last_message_type = $2,
    last_message_preview = $3,
    last_message_at = $4,
    customer_unread_count = $5,
    staff_unread_count = $6,
    status = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, customer_user_id, owner_sales_user_id, assignee_user_id, assignee_role, status, last_message_type, last_message_preview, last_message_at, customer_unread_count, staff_unread_count, created_at, updated_at, closed_at
`

type UpdateSupportConversationAfterMessageParams struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	LastMessageType     *string            `db:"last_message_type" json:"last_message_type"`
	LastMessagePreview  *string            `db:"last_message_preview" json:"last_message_preview"`
	LastMessageAt       pgtype.Timestamptz `db:"last_message_at" json:"last_message_at"`
	CustomerUnreadCount int32              `db:"customer_unread_count" json:"customer_unread_count"`
	StaffUnreadCount    int32              `db:"staff_unread_count" json:"staff_unread_count"`
	Status              string             `db:"status" json:"status"`
}

func (q *Queries) UpdateSupportConversationAfterMessage(ctx context.Context, arg UpdateSupportConversationAfterMessageParams) (SupportConversation, error) {
	row := q.db.QueryRow(ctx, updateSupportConversationAfterMessage,
		arg.ID,
		arg.LastMessageType,
		arg.LastMessagePreview,
		arg.LastMessageAt,
		arg.CustomerUnreadCount,
		arg.StaffUnreadCount,
		arg.Status,
	)
	var i SupportConversation
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.OwnerSalesUserID,
		&i.AssigneeUserID,
		&i.AssigneeRole,
		&i.Status,
		&i.LastMessageType,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.CustomerUnreadCount,
		&i.StaffUnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}
