// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracking.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listTrackingShipments = `-- name: ListTrackingShipments :many
SELECT id, order_id, waybill_no, carrier, shipped_at, created_at, updated_at
FROM order_tracking_shipments
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTrackingShipments(ctx context.Context, orderID uuid.UUID) ([]OrderTrackingShipment, error) {
	rows, err := q.db.Query(ctx, listTrackingShipments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderTrackingShipment
	for rows.Next() {
		var i OrderTrackingShipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.WaybillNo,
			&i.Carrier,
			&i.ShippedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrackingShipment = `-- name: UpsertTrackingShipment :one
INSERT INTO order_tracking_shipments (
    order_id,
    waybill_no,
    carrier,
    shipped_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (order_id, waybill_no)
DO UPDATE SET carrier = EXCLUDED.carrier,
              shipped_at = EXCLUDED.shipped_at,
              updated_at = now()
RETURNING id, order_id, waybill_no, carrier, shipped_at, created_at, updated_at
`

type UpsertTrackingShipmentParams struct {
	OrderID   uuid.UUID          `db:"order_id" json:"order_id"`
	WaybillNo string             `db:"waybill_no" json:"waybill_no"`
	Carrier   *string            `db:"carrier" json:"carrier"`
	ShippedAt pgtype.Timestamptz `db:"shipped_at" json:"shipped_at"`
}

func (q *Queries) UpsertTrackingShipment(ctx context.Context, arg UpsertTrackingShipmentParams) (OrderTrackingShipment, error) {
	row := q.db.QueryRow(ctx, upsertTrackingShipment,
		arg.OrderID,
		arg.WaybillNo,
		arg.Carrier,
		arg.ShippedAt,
	)
	var i OrderTrackingShipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.WaybillNo,
		&i.Carrier,
		&i.ShippedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
