// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlist.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWishlistItem = `-- name: CreateWishlistItem :exec
INSERT INTO wishlist_items (
    owner_user_id,
    sku_id
) VALUES (
    $1,
    $2
)
ON CONFLICT DO NOTHING
`

type CreateWishlistItemParams struct {
	OwnerUserID uuid.UUID `db:"owner_user_id" json:"owner_user_id"`
	SkuID       uuid.UUID `db:"sku_id" json:"sku_id"`
}

func (q *Queries) CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) error {
	_, err := q.db.Exec(ctx, createWishlistItem, arg.OwnerUserID, arg.SkuID)
	return err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :exec
DELETE FROM wishlist_items
WHERE owner_user_id = $1 AND sku_id = $2
`

type DeleteWishlistItemParams struct {
	OwnerUserID uuid.UUID `db:"owner_user_id" json:"owner_user_id"`
	SkuID       uuid.UUID `db:"sku_id" json:"sku_id"`
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error {
	_, err := q.db.Exec(ctx, deleteWishlistItem, arg.OwnerUserID, arg.SkuID)
	return err
}

const listWishlistItems = `-- name: ListWishlistItems :many
SELECT id, owner_user_id, sku_id, created_at
FROM wishlist_items
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWishlistItems(ctx context.Context, ownerUserID uuid.UUID) ([]WishlistItem, error) {
	rows, err := q.db.Query(ctx, listWishlistItems, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishlistItem
	for rows.Next() {
		var i WishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.SkuID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
