// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/teamdsb/tmo/services/commerce/internal/http/oapi/common"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CartImportJobType.
const (
	CartImportJobTypeCARTIMPORT           CartImportJobType = "CART_IMPORT"
	CartImportJobTypePRODUCTIMPORT        CartImportJobType = "PRODUCT_IMPORT"
	CartImportJobTypePRODUCTREQUESTEXPORT CartImportJobType = "PRODUCT_REQUEST_EXPORT"
	CartImportJobTypeSHIPMENTIMPORT       CartImportJobType = "SHIPMENT_IMPORT"
)

// Defines values for CartImportPendingItemMatchType.
const (
	AMBIGUOUS CartImportPendingItemMatchType = "AMBIGUOUS"
	NOTFOUND  CartImportPendingItemMatchType = "NOT_FOUND"
)

// Defines values for ImportJobType.
const (
	ImportJobTypeCARTIMPORT           ImportJobType = "CART_IMPORT"
	ImportJobTypePRODUCTIMPORT        ImportJobType = "PRODUCT_IMPORT"
	ImportJobTypePRODUCTREQUESTEXPORT ImportJobType = "PRODUCT_REQUEST_EXPORT"
	ImportJobTypeSHIPMENTIMPORT       ImportJobType = "SHIPMENT_IMPORT"
)

// Defines values for JobStatus.
const (
	FAILED    JobStatus = "FAILED"
	PENDING   JobStatus = "PENDING"
	RUNNING   JobStatus = "RUNNING"
	SUCCEEDED JobStatus = "SUCCEEDED"
)

// Defines values for MessageSenderType.
const (
	Ai       MessageSenderType = "ai"
	Customer MessageSenderType = "customer"
	Staff    MessageSenderType = "staff"
)

// Defines values for OrderStatus.
const (
	OrderStatusCANCELLED  OrderStatus = "CANCELLED"
	OrderStatusCLOSED     OrderStatus = "CLOSED"
	OrderStatusCONFIRMED  OrderStatus = "CONFIRMED"
	OrderStatusDELIVERED  OrderStatus = "DELIVERED"
	OrderStatusPAID       OrderStatus = "PAID"
	OrderStatusPAYFAILED  OrderStatus = "PAY_FAILED"
	OrderStatusPAYPENDING OrderStatus = "PAY_PENDING"
	OrderStatusSHIPPED    OrderStatus = "SHIPPED"
	OrderStatusSUBMITTED  OrderStatus = "SUBMITTED"
)

// Defines values for PriceInquiryStatus.
const (
	PriceInquiryStatusCLOSED    PriceInquiryStatus = "CLOSED"
	PriceInquiryStatusOPEN      PriceInquiryStatus = "OPEN"
	PriceInquiryStatusRESPONDED PriceInquiryStatus = "RESPONDED"
)

// Defines values for TicketStatus.
const (
	TicketStatusCLOSED     TicketStatus = "CLOSED"
	TicketStatusINPROGRESS TicketStatus = "IN_PROGRESS"
	TicketStatusOPEN       TicketStatus = "OPEN"
	TicketStatusRESOLVED   TicketStatus = "RESOLVED"
)

// Defines values for UpdatePriceInquiryRequestStatus.
const (
	UpdatePriceInquiryRequestStatusCLOSED    UpdatePriceInquiryRequestStatus = "CLOSED"
	UpdatePriceInquiryRequestStatusOPEN      UpdatePriceInquiryRequestStatus = "OPEN"
	UpdatePriceInquiryRequestStatusRESPONDED UpdatePriceInquiryRequestStatus = "RESPONDED"
)

// Defines values for GetInquiriesPriceParamsStatus.
const (
	CLOSED    GetInquiriesPriceParamsStatus = "CLOSED"
	OPEN      GetInquiriesPriceParamsStatus = "OPEN"
	RESPONDED GetInquiriesPriceParamsStatus = "RESPONDED"
)

// AddCartItemRequest defines model for AddCartItemRequest.
type AddCartItemRequest struct {
	Qty   int                `json:"qty"`
	SkuId openapi_types.UUID `json:"skuId"`
}

// Address defines model for Address.
type Address struct {
	City          *string `json:"city,omitempty"`
	Detail        string  `json:"detail"`
	District      *string `json:"district,omitempty"`
	Province      *string `json:"province,omitempty"`
	ReceiverName  string  `json:"receiverName"`
	ReceiverPhone string  `json:"receiverPhone"`
}

// AfterSalesMessage defines model for AfterSalesMessage.
type AfterSalesMessage struct {
	Content      string              `json:"content"`
	CreatedAt    time.Time           `json:"createdAt"`
	Id           openapi_types.UUID  `json:"id"`
	SenderType   MessageSenderType   `json:"senderType"`
	SenderUserId *openapi_types.UUID `json:"senderUserId"`
	TicketId     openapi_types.UUID  `json:"ticketId"`
}

// AfterSalesTicket defines model for AfterSalesTicket.
type AfterSalesTicket struct {
	AssignedStaffUserId *openapi_types.UUID `json:"assignedStaffUserId"`
	CreatedAt           time.Time           `json:"createdAt"`
	Description         string              `json:"description"`
	Id                  openapi_types.UUID  `json:"id"`
	OrderId             *openapi_types.UUID `json:"orderId"`
	Status              TicketStatus        `json:"status"`
	Subject             string              `json:"subject"`
	UpdatedAt           *time.Time          `json:"updatedAt"`
}

// Cart defines model for Cart.
type Cart struct {
	Items     []CartItem `json:"items"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// CartImportAddedItem defines model for CartImportAddedItem.
type CartImportAddedItem struct {
	Qty   int                `json:"qty"`
	RowNo int                `json:"rowNo"`
	SkuId openapi_types.UUID `json:"skuId"`
}

// CartImportCandidate defines model for CartImportCandidate.
type CartImportCandidate struct {
	Sku SKU `json:"sku"`
}

// CartImportJob defines model for CartImportJob.
type CartImportJob struct {
	CreatedAt      time.Time          `json:"createdAt"`
	ErrorReportUrl *string            `json:"errorReportUrl"`
	Id             openapi_types.UUID `json:"id"`
	Progress       int                `json:"progress"`
	Result         *CartImportResult  `json:"result,omitempty"`
	ResultFileUrl  *string            `json:"resultFileUrl"`
	Status         JobStatus          `json:"status"`
	Type           CartImportJobType  `json:"type"`
}

// CartImportJobType defines model for CartImportJob.Type.
type CartImportJobType string

// CartImportPendingItem defines model for CartImportPendingItem.
type CartImportPendingItem struct {
	Candidates []CartImportCandidate          `json:"candidates"`
	MatchType  CartImportPendingItemMatchType `json:"matchType"`
	RawName    string                         `json:"rawName"`
	RawQty     *string                        `json:"rawQty"`
	RawSpec    *string                        `json:"rawSpec"`
	RowNo      int                            `json:"rowNo"`
}

// CartImportPendingItemMatchType defines model for CartImportPendingItem.MatchType.
type CartImportPendingItemMatchType string

// CartImportResult defines model for CartImportResult.
type CartImportResult struct {
	AutoAddedCount int                     `json:"autoAddedCount"`
	AutoAddedItems []CartImportAddedItem   `json:"autoAddedItems"`
	PendingCount   int                     `json:"pendingCount"`
	PendingItems   []CartImportPendingItem `json:"pendingItems"`
}

// CartImportSelection defines model for CartImportSelection.
type CartImportSelection struct {
	Qty   *int               `json:"qty"`
	RowNo int                `json:"rowNo"`
	SkuId openapi_types.UUID `json:"skuId"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	Id  openapi_types.UUID `json:"id"`
	Qty int                `json:"qty"`
	Sku SKU                `json:"sku"`
}

// Category defines model for Category.
type Category struct {
	Id       openapi_types.UUID  `json:"id"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId"`
	Sort     int                 `json:"sort"`
}

// ConfirmCartImportRequest defines model for ConfirmCartImportRequest.
type ConfirmCartImportRequest struct {
	Selections []CartImportSelection `json:"selections"`
}

// CreateAfterSalesTicket defines model for CreateAfterSalesTicket.
type CreateAfterSalesTicket struct {
	Attachments *[]string           `json:"attachments,omitempty"`
	Description string              `json:"description"`
	OrderId     *openapi_types.UUID `json:"orderId"`
	Subject     string              `json:"subject"`
}

// CreateCatalogProductRequest defines model for CreateCatalogProductRequest.
type CreateCatalogProductRequest struct {
	CategoryId       openapi_types.UUID `json:"categoryId"`
	CoverImageUrl    *string            `json:"coverImageUrl,omitempty"`
	Description      *string            `json:"description,omitempty"`
	FilterDimensions *[]string          `json:"filterDimensions,omitempty"`
	Images           *[]string          `json:"images,omitempty"`
	Name             string             `json:"name"`
	Tags             *[]string          `json:"tags,omitempty"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId"`
	Sort     *int                `json:"sort,omitempty"`
}

// CreateInquiryMessage defines model for CreateInquiryMessage.
type CreateInquiryMessage struct {
	Content string `json:"content"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Address Address `json:"address"`
	Items   []struct {
		Qty   int                `json:"qty"`
		SkuId openapi_types.UUID `json:"skuId"`
	} `json:"items"`
	Remark *string `json:"remark,omitempty"`
}

// CreatePriceInquiry defines model for CreatePriceInquiry.
type CreatePriceInquiry struct {
	Message string              `json:"message"`
	OrderId *openapi_types.UUID `json:"orderId"`
	SkuId   *openapi_types.UUID `json:"skuId"`
}

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	CategoryId *openapi_types.UUID `json:"categoryId"`
	Color      *string             `json:"color,omitempty"`
	Dimensions *string             `json:"dimensions,omitempty"`
	Material   *string             `json:"material,omitempty"`
	Name       string              `json:"name"`
	Note       *string             `json:"note,omitempty"`

	// Qty Free-form, e.g., '10 boxes' or '5 pcs'
	Qty                *string   `json:"qty,omitempty"`
	ReferenceImageUrls *[]string `json:"referenceImageUrls,omitempty"`
	Spec               *string   `json:"spec,omitempty"`
}

// CreateSkuRequest defines model for CreateSkuRequest.
type CreateSkuRequest struct {
	Attributes *map[string]string `json:"attributes,omitempty"`
	IsActive   *bool              `json:"isActive,omitempty"`
	Name       string             `json:"name"`
	PriceTiers *[]PriceTier       `json:"priceTiers,omitempty"`
	SkuCode    *string            `json:"skuCode,omitempty"`

	// Spec Primary spec label used for matching (e.g., size/grade); store here and avoid duplicating in attributes
	Spec *string `json:"spec,omitempty"`
	Unit *string `json:"unit,omitempty"`
}

// CreateTicketMessage defines model for CreateTicketMessage.
type CreateTicketMessage struct {
	Content string `json:"content"`
}

// CreateUserAddressRequest defines model for CreateUserAddressRequest.
type CreateUserAddressRequest struct {
	Detail        string `json:"detail"`
	IsDefault     *bool  `json:"isDefault,omitempty"`
	ReceiverName  string `json:"receiverName"`
	ReceiverPhone string `json:"receiverPhone"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = externalRef0.ErrorResponse

// ImportJob defines model for ImportJob.
type ImportJob struct {
	CreatedAt      time.Time          `json:"createdAt"`
	ErrorReportUrl *string            `json:"errorReportUrl"`
	Id             openapi_types.UUID `json:"id"`
	Progress       int                `json:"progress"`
	ResultFileUrl  *string            `json:"resultFileUrl"`
	Status         JobStatus          `json:"status"`
	Type           ImportJobType      `json:"type"`
}

// ImportJobType defines model for ImportJob.Type.
type ImportJobType string

// InquiryMessage defines model for InquiryMessage.
type InquiryMessage struct {
	Content      string              `json:"content"`
	CreatedAt    time.Time           `json:"createdAt"`
	Id           openapi_types.UUID  `json:"id"`
	InquiryId    openapi_types.UUID  `json:"inquiryId"`
	SenderType   MessageSenderType   `json:"senderType"`
	SenderUserId *openapi_types.UUID `json:"senderUserId"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// ListAddressesResponse defines model for ListAddressesResponse.
type ListAddressesResponse struct {
	Items []UserAddress `json:"items"`
}

// MessageSenderType defines model for MessageSenderType.
type MessageSenderType string

// Order defines model for Order.
type Order struct {
	Address   *Address           `json:"address,omitempty"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Items     []OrderItem        `json:"items"`
	Remark    *string            `json:"remark,omitempty"`
	Status    OrderStatus        `json:"status"`
	UpdatedAt *time.Time         `json:"updatedAt,omitempty"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	Qty int `json:"qty"`
	Sku SKU `json:"sku"`

	// UnitPriceFen Final price per unit at order time, in fen (1/100 yuan), integer only
	UnitPriceFen int64 `json:"unitPriceFen"`
}

// OrderStatsResponse defines model for OrderStatsResponse.
type OrderStatsResponse struct {
	Items []OrderStatusStat `json:"items"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrderStatusStat defines model for OrderStatusStat.
type OrderStatusStat struct {
	Count  int         `json:"count"`
	Status OrderStatus `json:"status"`
}

// PagedAfterSalesMessageList defines model for PagedAfterSalesMessageList.
type PagedAfterSalesMessageList struct {
	Items    []AfterSalesMessage `json:"items"`
	Page     int                 `json:"page"`
	PageSize int                 `json:"pageSize"`
	Total    int                 `json:"total"`
}

// PagedAfterSalesTicketList defines model for PagedAfterSalesTicketList.
type PagedAfterSalesTicketList struct {
	Items    []AfterSalesTicket `json:"items"`
	Page     int                `json:"page"`
	PageSize int                `json:"pageSize"`
	Total    int                `json:"total"`
}

// PagedInquiryMessageList defines model for PagedInquiryMessageList.
type PagedInquiryMessageList struct {
	Items    []InquiryMessage `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// PagedOrderList defines model for PagedOrderList.
type PagedOrderList struct {
	Items    []Order `json:"items"`
	Page     int     `json:"page"`
	PageSize int     `json:"pageSize"`
	Total    int     `json:"total"`
}

// PagedPriceInquiryList defines model for PagedPriceInquiryList.
type PagedPriceInquiryList struct {
	Items    []PriceInquiry `json:"items"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
	Total    int            `json:"total"`
}

// PagedProductList defines model for PagedProductList.
type PagedProductList struct {
	Items    []ProductSummary `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// PagedProductRequestList defines model for PagedProductRequestList.
type PagedProductRequestList struct {
	Items    []ProductRequest `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// PriceInquiry defines model for PriceInquiry.
type PriceInquiry struct {
	AssignedSalesUserId *openapi_types.UUID `json:"assignedSalesUserId"`
	CreatedAt           time.Time           `json:"createdAt"`
	CreatedByUserId     openapi_types.UUID  `json:"createdByUserId"`
	Id                  openapi_types.UUID  `json:"id"`
	Message             string              `json:"message"`
	OrderId             *openapi_types.UUID `json:"orderId"`

	// ResponseNote Optional summary note; detailed replies via messages
	ResponseNote *string             `json:"responseNote"`
	SkuId        *openapi_types.UUID `json:"skuId"`
	Status       PriceInquiryStatus  `json:"status"`
	UpdatedAt    *time.Time          `json:"updatedAt"`
}

// PriceInquiryStatus defines model for PriceInquiry.Status.
type PriceInquiryStatus string

// PriceTier defines model for PriceTier.
type PriceTier struct {
	// MaxQty null means no upper bound
	MaxQty *int `json:"maxQty"`
	MinQty int  `json:"minQty"`

	// UnitPriceFen Unit price in fen (1/100 yuan), integer only
	UnitPriceFen int64 `json:"unitPriceFen"`
}

// ProductDetail defines model for ProductDetail.
type ProductDetail struct {
	Product struct {
		CategoryId  openapi_types.UUID `json:"categoryId"`
		Description *string            `json:"description,omitempty"`

		// FilterDimensions For multi-level filtering, e.g., material -> length -> size
		FilterDimensions *[]string          `json:"filterDimensions,omitempty"`
		Id               openapi_types.UUID `json:"id"`
		Images           *[]string          `json:"images,omitempty"`
		Name             string             `json:"name"`
	} `json:"product"`
	Skus []SKU `json:"skus"`
}

// ProductRequest defines model for ProductRequest.
type ProductRequest struct {
	CategoryId         *openapi_types.UUID `json:"categoryId"`
	Color              *string             `json:"color,omitempty"`
	CreatedAt          time.Time           `json:"createdAt"`
	CreatedByUserId    openapi_types.UUID  `json:"createdByUserId"`
	Dimensions         *string             `json:"dimensions,omitempty"`
	Id                 openapi_types.UUID  `json:"id"`
	Material           *string             `json:"material,omitempty"`
	Name               string              `json:"name"`
	Note               *string             `json:"note,omitempty"`
	Qty                *string             `json:"qty,omitempty"`
	ReferenceImageUrls *[]string           `json:"referenceImageUrls,omitempty"`
	Spec               *string             `json:"spec,omitempty"`
}

// ProductRequestAsset defines model for ProductRequestAsset.
type ProductRequestAsset struct {
	ContentType string `json:"contentType"`
	Size        int64  `json:"size"`
	Url         string `json:"url"`
}

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	CategoryId    openapi_types.UUID `json:"categoryId"`
	CoverImageUrl *string            `json:"coverImageUrl,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
	Tags          *[]string          `json:"tags,omitempty"`
}

// SKU defines model for SKU.
type SKU struct {
	Attributes *map[string]string `json:"attributes,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	IsActive   bool               `json:"isActive"`
	Name       string             `json:"name"`
	PriceTiers *[]PriceTier       `json:"priceTiers,omitempty"`
	SkuCode    *string            `json:"skuCode,omitempty"`

	// Spec Canonical spec label for matching; do not duplicate in attributes
	Spec  *string            `json:"spec,omitempty"`
	SpuId openapi_types.UUID `json:"spuId"`
	Unit  *string            `json:"unit,omitempty"`
}

// TicketStatus defines model for TicketStatus.
type TicketStatus string

// TrackingInfo defines model for TrackingInfo.
type TrackingInfo struct {
	OrderId   openapi_types.UUID `json:"orderId"`
	Shipments []struct {
		Carrier   *string    `json:"carrier"`
		ShippedAt *time.Time `json:"shippedAt"`
		WaybillNo string     `json:"waybillNo"`
	} `json:"shipments"`
}

// UpdateAfterSalesTicketRequest defines model for UpdateAfterSalesTicketRequest.
type UpdateAfterSalesTicketRequest struct {
	AssignedStaffUserId *openapi_types.UUID `json:"assignedStaffUserId"`
	Status              *TicketStatus       `json:"status,omitempty"`
}

// UpdateCatalogProductRequest defines model for UpdateCatalogProductRequest.
type UpdateCatalogProductRequest struct {
	CategoryId       *openapi_types.UUID `json:"categoryId,omitempty"`
	CoverImageUrl    *string             `json:"coverImageUrl"`
	Description      *string             `json:"description"`
	FilterDimensions *[]string           `json:"filterDimensions,omitempty"`
	Images           *[]string           `json:"images,omitempty"`
	Name             *string             `json:"name,omitempty"`
	Tags             *[]string           `json:"tags,omitempty"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	Name     *string             `json:"name,omitempty"`
	ParentId *openapi_types.UUID `json:"parentId"`
	Sort     *int                `json:"sort,omitempty"`
}

// UpdatePriceInquiryRequest defines model for UpdatePriceInquiryRequest.
type UpdatePriceInquiryRequest struct {
	AssignedSalesUserId *openapi_types.UUID `json:"assignedSalesUserId"`

	// ResponseNote Optional summary note; detailed replies via messages
	ResponseNote *string                          `json:"responseNote"`
	Status       *UpdatePriceInquiryRequestStatus `json:"status,omitempty"`
}

// UpdatePriceInquiryRequestStatus defines model for UpdatePriceInquiryRequest.Status.
type UpdatePriceInquiryRequestStatus string

// UpdateTrackingRequest defines model for UpdateTrackingRequest.
type UpdateTrackingRequest struct {
	Shipments []struct {
		Carrier   *string    `json:"carrier"`
		ShippedAt *time.Time `json:"shippedAt"`
		WaybillNo string     `json:"waybillNo"`
	} `json:"shipments"`
}

// UpdateUserAddressRequest defines model for UpdateUserAddressRequest.
type UpdateUserAddressRequest struct {
	Detail        *string `json:"detail,omitempty"`
	IsDefault     *bool   `json:"isDefault,omitempty"`
	ReceiverName  *string `json:"receiverName,omitempty"`
	ReceiverPhone *string `json:"receiverPhone,omitempty"`
}

// UserAddress defines model for UserAddress.
type UserAddress struct {
	CreatedAt     time.Time          `json:"createdAt"`
	Detail        string             `json:"detail"`
	Id            openapi_types.UUID `json:"id"`
	IsDefault     bool               `json:"isDefault"`
	ReceiverName  string             `json:"receiverName"`
	ReceiverPhone string             `json:"receiverPhone"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

// WishlistItem defines model for WishlistItem.
type WishlistItem struct {
	CreatedAt time.Time `json:"createdAt"`
	Sku       SKU       `json:"sku"`
}

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetAfterSalesTicketsParams defines parameters for GetAfterSalesTickets.
type GetAfterSalesTicketsParams struct {
	Status   *TicketStatus       `form:"status,omitempty" json:"status,omitempty"`
	OrderId  *openapi_types.UUID `form:"orderId,omitempty" json:"orderId,omitempty"`
	Page     *int                `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int                `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetAfterSalesTicketsTicketIdMessagesParams defines parameters for GetAfterSalesTicketsTicketIdMessages.
type GetAfterSalesTicketsTicketIdMessagesParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostCartImportJobsMultipartBody defines parameters for PostCartImportJobs.
type PostCartImportJobsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PatchCartItemsItemIdJSONBody defines parameters for PatchCartItemsItemId.
type PatchCartItemsItemIdJSONBody struct {
	Qty int `json:"qty"`
}

// GetCatalogProductsParams defines parameters for GetCatalogProducts.
type GetCatalogProductsParams struct {
	Q          *string             `form:"q,omitempty" json:"q,omitempty"`
	CategoryId *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	Page       *int                `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *int                `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetInquiriesPriceParams defines parameters for GetInquiriesPrice.
type GetInquiriesPriceParams struct {
	Status   *GetInquiriesPriceParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Page     *int                           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int                           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetInquiriesPriceParamsStatus defines parameters for GetInquiriesPrice.
type GetInquiriesPriceParamsStatus string

// GetInquiriesPriceInquiryIdMessagesParams defines parameters for GetInquiriesPriceInquiryIdMessages.
type GetInquiriesPriceInquiryIdMessagesParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	CustomerId       *openapi_types.UUID `form:"customerId,omitempty" json:"customerId,omitempty"`
	OwnerSalesUserId *openapi_types.UUID `form:"ownerSalesUserId,omitempty" json:"ownerSalesUserId,omitempty"`
	Status           *OrderStatus        `form:"status,omitempty" json:"status,omitempty"`
	Page             *int                `form:"page,omitempty" json:"page,omitempty"`
	PageSize         *int                `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostOrdersParams defines parameters for PostOrders.
type PostOrdersParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetProductRequestsParams defines parameters for GetProductRequests.
type GetProductRequestsParams struct {
	CreatedAfter  *time.Time `form:"createdAfter,omitempty" json:"createdAfter,omitempty"`
	CreatedBefore *time.Time `form:"createdBefore,omitempty" json:"createdBefore,omitempty"`
	Page          *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize      *int       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostProductRequestsAssetsMultipartBody defines parameters for PostProductRequestsAssets.
type PostProductRequestsAssetsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PostShipmentsImportJobsMultipartBody defines parameters for PostShipmentsImportJobs.
type PostShipmentsImportJobsMultipartBody struct {
	ExcelFile openapi_types.File `json:"excelFile"`
}

// PostWishlistJSONBody defines parameters for PostWishlist.
type PostWishlistJSONBody struct {
	SkuId openapi_types.UUID `json:"skuId"`
}

// PostAddressesJSONRequestBody defines body for PostAddresses for application/json ContentType.
type PostAddressesJSONRequestBody = CreateUserAddressRequest

// PatchAddressesAddressIdJSONRequestBody defines body for PatchAddressesAddressId for application/json ContentType.
type PatchAddressesAddressIdJSONRequestBody = UpdateUserAddressRequest

// PostAfterSalesTicketsJSONRequestBody defines body for PostAfterSalesTickets for application/json ContentType.
type PostAfterSalesTicketsJSONRequestBody = CreateAfterSalesTicket

// PatchAfterSalesTicketsTicketIdJSONRequestBody defines body for PatchAfterSalesTicketsTicketId for application/json ContentType.
type PatchAfterSalesTicketsTicketIdJSONRequestBody = UpdateAfterSalesTicketRequest

// PostAfterSalesTicketsTicketIdMessagesJSONRequestBody defines body for PostAfterSalesTicketsTicketIdMessages for application/json ContentType.
type PostAfterSalesTicketsTicketIdMessagesJSONRequestBody = CreateTicketMessage

// PostCartImportJobsMultipartRequestBody defines body for PostCartImportJobs for multipart/form-data ContentType.
type PostCartImportJobsMultipartRequestBody PostCartImportJobsMultipartBody

// PostCartImportJobsJobIdConfirmJSONRequestBody defines body for PostCartImportJobsJobIdConfirm for application/json ContentType.
type PostCartImportJobsJobIdConfirmJSONRequestBody = ConfirmCartImportRequest

// PostCartItemsJSONRequestBody defines body for PostCartItems for application/json ContentType.
type PostCartItemsJSONRequestBody = AddCartItemRequest

// PatchCartItemsItemIdJSONRequestBody defines body for PatchCartItemsItemId for application/json ContentType.
type PatchCartItemsItemIdJSONRequestBody PatchCartItemsItemIdJSONBody

// PostCatalogCategoriesJSONRequestBody defines body for PostCatalogCategories for application/json ContentType.
type PostCatalogCategoriesJSONRequestBody = CreateCategoryRequest

// PatchCatalogCategoriesCategoryIdJSONRequestBody defines body for PatchCatalogCategoriesCategoryId for application/json ContentType.
type PatchCatalogCategoriesCategoryIdJSONRequestBody = UpdateCategoryRequest

// PostCatalogProductsJSONRequestBody defines body for PostCatalogProducts for application/json ContentType.
type PostCatalogProductsJSONRequestBody = CreateCatalogProductRequest

// PatchCatalogProductsSpuIdJSONRequestBody defines body for PatchCatalogProductsSpuId for application/json ContentType.
type PatchCatalogProductsSpuIdJSONRequestBody = UpdateCatalogProductRequest

// PostCatalogProductsSpuIdSkusJSONRequestBody defines body for PostCatalogProductsSpuIdSkus for application/json ContentType.
type PostCatalogProductsSpuIdSkusJSONRequestBody = CreateSkuRequest

// PostInquiriesPriceJSONRequestBody defines body for PostInquiriesPrice for application/json ContentType.
type PostInquiriesPriceJSONRequestBody = CreatePriceInquiry

// PatchInquiriesPriceInquiryIdJSONRequestBody defines body for PatchInquiriesPriceInquiryId for application/json ContentType.
type PatchInquiriesPriceInquiryIdJSONRequestBody = UpdatePriceInquiryRequest

// PostInquiriesPriceInquiryIdMessagesJSONRequestBody defines body for PostInquiriesPriceInquiryIdMessages for application/json ContentType.
type PostInquiriesPriceInquiryIdMessagesJSONRequestBody = CreateInquiryMessage

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = CreateOrderRequest

// PostOrdersOrderIdTrackingJSONRequestBody defines body for PostOrdersOrderIdTracking for application/json ContentType.
type PostOrdersOrderIdTrackingJSONRequestBody = UpdateTrackingRequest

// PostProductRequestsJSONRequestBody defines body for PostProductRequests for application/json ContentType.
type PostProductRequestsJSONRequestBody = CreateProductRequest

// PostProductRequestsAssetsMultipartRequestBody defines body for PostProductRequestsAssets for multipart/form-data ContentType.
type PostProductRequestsAssetsMultipartRequestBody PostProductRequestsAssetsMultipartBody

// PostShipmentsImportJobsMultipartRequestBody defines body for PostShipmentsImportJobs for multipart/form-data ContentType.
type PostShipmentsImportJobsMultipartRequestBody PostShipmentsImportJobsMultipartBody

// PostWishlistJSONRequestBody defines body for PostWishlist for application/json ContentType.
type PostWishlistJSONRequestBody PostWishlistJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List current user's addresses
	// (GET /addresses)
	GetAddresses(c *gin.Context)
	// Create current user's address
	// (POST /addresses)
	PostAddresses(c *gin.Context)
	// Delete current user's address
	// (DELETE /addresses/{addressId})
	DeleteAddressesAddressId(c *gin.Context, addressId openapi_types.UUID)
	// Update current user's address
	// (PATCH /addresses/{addressId})
	PatchAddressesAddressId(c *gin.Context, addressId openapi_types.UUID)
	// List after-sales tickets
	// (GET /after-sales/tickets)
	GetAfterSalesTickets(c *gin.Context, params GetAfterSalesTicketsParams)
	// Create after-sales ticket
	// (POST /after-sales/tickets)
	PostAfterSalesTickets(c *gin.Context)
	// Get after-sales ticket detail
	// (GET /after-sales/tickets/{ticketId})
	GetAfterSalesTicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// Update after-sales ticket (status/assignee)
	// (PATCH /after-sales/tickets/{ticketId})
	PatchAfterSalesTicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// List ticket messages
	// (GET /after-sales/tickets/{ticketId}/messages)
	GetAfterSalesTicketsTicketIdMessages(c *gin.Context, ticketId openapi_types.UUID, params GetAfterSalesTicketsTicketIdMessagesParams)
	// Post a message in ticket (customer/staff/AI)
	// (POST /after-sales/tickets/{ticketId}/messages)
	PostAfterSalesTicketsTicketIdMessages(c *gin.Context, ticketId openapi_types.UUID)
	// Get current cart
	// (GET /cart)
	GetCart(c *gin.Context)
	// Upload Excel for bulk add-to-cart (creates an import job)
	// (POST /cart/import-jobs)
	PostCartImportJobs(c *gin.Context)
	// Get cart import job status and matching result
	// (GET /cart/import-jobs/{jobId})
	GetCartImportJobsJobId(c *gin.Context, jobId openapi_types.UUID)
	// Confirm SKU selections for ambiguous rows
	// (POST /cart/import-jobs/{jobId}/confirm)
	PostCartImportJobsJobIdConfirm(c *gin.Context, jobId openapi_types.UUID)
	// Add item to cart
	// (POST /cart/items)
	PostCartItems(c *gin.Context)
	// Remove cart item
	// (DELETE /cart/items/{itemId})
	DeleteCartItemsItemId(c *gin.Context, itemId openapi_types.UUID)
	// Update cart item qty
	// (PATCH /cart/items/{itemId})
	PatchCartItemsItemId(c *gin.Context, itemId openapi_types.UUID)
	// List categories
	// (GET /catalog/categories)
	GetCatalogCategories(c *gin.Context)
	// Create category
	// (POST /catalog/categories)
	PostCatalogCategories(c *gin.Context)
	// Delete category
	// (DELETE /catalog/categories/{categoryId})
	DeleteCatalogCategoriesCategoryId(c *gin.Context, categoryId openapi_types.UUID)
	// Get category
	// (GET /catalog/categories/{categoryId})
	GetCatalogCategoriesCategoryId(c *gin.Context, categoryId openapi_types.UUID)
	// Update category
	// (PATCH /catalog/categories/{categoryId})
	PatchCatalogCategoriesCategoryId(c *gin.Context, categoryId openapi_types.UUID)
	// Search/list products (SPU list)
	// (GET /catalog/products)
	GetCatalogProducts(c *gin.Context, params GetCatalogProductsParams)
	// Create product (SPU)
	// (POST /catalog/products)
	PostCatalogProducts(c *gin.Context)
	// Delete product (SPU)
	// (DELETE /catalog/products/{spuId})
	DeleteCatalogProductsSpuId(c *gin.Context, spuId openapi_types.UUID)
	// Get product detail (SPU + SKU summary)
	// (GET /catalog/products/{spuId})
	GetCatalogProductsSpuId(c *gin.Context, spuId openapi_types.UUID)
	// Update product (SPU)
	// (PATCH /catalog/products/{spuId})
	PatchCatalogProductsSpuId(c *gin.Context, spuId openapi_types.UUID)
	// Create SKU for product
	// (POST /catalog/products/{spuId}/skus)
	PostCatalogProductsSpuIdSkus(c *gin.Context, spuId openapi_types.UUID)
	// List price inquiries
	// (GET /inquiries/price)
	GetInquiriesPrice(c *gin.Context, params GetInquiriesPriceParams)
	// Create price negotiation inquiry ("feel expensive, let's talk")
	// (POST /inquiries/price)
	PostInquiriesPrice(c *gin.Context)
	// Get price inquiry detail
	// (GET /inquiries/price/{inquiryId})
	GetInquiriesPriceInquiryId(c *gin.Context, inquiryId openapi_types.UUID)
	// Update price inquiry (status/assignee/summary)
	// (PATCH /inquiries/price/{inquiryId})
	PatchInquiriesPriceInquiryId(c *gin.Context, inquiryId openapi_types.UUID)
	// List price inquiry messages
	// (GET /inquiries/price/{inquiryId}/messages)
	GetInquiriesPriceInquiryIdMessages(c *gin.Context, inquiryId openapi_types.UUID, params GetInquiriesPriceInquiryIdMessagesParams)
	// Post a message in price inquiry
	// (POST /inquiries/price/{inquiryId}/messages)
	PostInquiriesPriceInquiryIdMessages(c *gin.Context, inquiryId openapi_types.UUID)
	// List orders (scope by role)
	// (GET /orders)
	GetOrders(c *gin.Context, params GetOrdersParams)
	// Submit intent order
	// (POST /orders)
	PostOrders(c *gin.Context, params PostOrdersParams)
	// Get current user's order status counts
	// (GET /orders/stats)
	GetOrdersStats(c *gin.Context)
	// Get my order detail
	// (GET /orders/{orderId})
	GetOrdersOrderId(c *gin.Context, orderId openapi_types.UUID)
	// Get tracking info (waybill numbers)
	// (GET /orders/{orderId}/tracking)
	GetOrdersOrderIdTracking(c *gin.Context, orderId openapi_types.UUID)
	// Add/update tracking info (procurement)
	// (POST /orders/{orderId}/tracking)
	PostOrdersOrderIdTracking(c *gin.Context, orderId openapi_types.UUID)
	// List product requests ("can't find product")
	// (GET /product-requests)
	GetProductRequests(c *gin.Context, params GetProductRequestsParams)
	// Submit "can't find product" request
	// (POST /product-requests)
	PostProductRequests(c *gin.Context)
	// Upload product request asset
	// (POST /product-requests/assets)
	PostProductRequestsAssets(c *gin.Context)
	// Upload Excel for bulk waybill import (procurement)
	// (POST /shipments/import-jobs)
	PostShipmentsImportJobs(c *gin.Context)
	// Get wishlist (favorites)
	// (GET /wishlist)
	GetWishlist(c *gin.Context)
	// Add SKU to wishlist
	// (POST /wishlist)
	PostWishlist(c *gin.Context)
	// Remove SKU from wishlist
	// (DELETE /wishlist/{skuId})
	DeleteWishlistSkuId(c *gin.Context, skuId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAddresses operation middleware
func (siw *ServerInterfaceWrapper) GetAddresses(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAddresses(c)
}

// PostAddresses operation middleware
func (siw *ServerInterfaceWrapper) PostAddresses(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAddresses(c)
}

// DeleteAddressesAddressId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAddressesAddressId(c *gin.Context) {

	var err error

	// ------------- Path parameter "addressId" -------------
	var addressId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "addressId", c.Param("addressId"), &addressId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter addressId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAddressesAddressId(c, addressId)
}

// PatchAddressesAddressId operation middleware
func (siw *ServerInterfaceWrapper) PatchAddressesAddressId(c *gin.Context) {

	var err error

	// ------------- Path parameter "addressId" -------------
	var addressId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "addressId", c.Param("addressId"), &addressId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter addressId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchAddressesAddressId(c, addressId)
}

// GetAfterSalesTickets operation middleware
func (siw *ServerInterfaceWrapper) GetAfterSalesTickets(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAfterSalesTicketsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "orderId" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderId", c.Request.URL.Query(), &params.OrderId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAfterSalesTickets(c, params)
}

// PostAfterSalesTickets operation middleware
func (siw *ServerInterfaceWrapper) PostAfterSalesTickets(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAfterSalesTickets(c)
}

// GetAfterSalesTicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) GetAfterSalesTicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", c.Param("ticketId"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticketId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAfterSalesTicketsTicketId(c, ticketId)
}

// PatchAfterSalesTicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) PatchAfterSalesTicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", c.Param("ticketId"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticketId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchAfterSalesTicketsTicketId(c, ticketId)
}

// GetAfterSalesTicketsTicketIdMessages operation middleware
func (siw *ServerInterfaceWrapper) GetAfterSalesTicketsTicketIdMessages(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", c.Param("ticketId"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticketId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAfterSalesTicketsTicketIdMessagesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAfterSalesTicketsTicketIdMessages(c, ticketId, params)
}

// PostAfterSalesTicketsTicketIdMessages operation middleware
func (siw *ServerInterfaceWrapper) PostAfterSalesTicketsTicketIdMessages(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", c.Param("ticketId"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticketId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAfterSalesTicketsTicketIdMessages(c, ticketId)
}

// GetCart operation middleware
func (siw *ServerInterfaceWrapper) GetCart(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCart(c)
}

// PostCartImportJobs operation middleware
func (siw *ServerInterfaceWrapper) PostCartImportJobs(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCartImportJobs(c)
}

// GetCartImportJobsJobId operation middleware
func (siw *ServerInterfaceWrapper) GetCartImportJobsJobId(c *gin.Context) {

	var err error

	// ------------- Path parameter "jobId" -------------
	var jobId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "jobId", c.Param("jobId"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter jobId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCartImportJobsJobId(c, jobId)
}

// PostCartImportJobsJobIdConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostCartImportJobsJobIdConfirm(c *gin.Context) {

	var err error

	// ------------- Path parameter "jobId" -------------
	var jobId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "jobId", c.Param("jobId"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter jobId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCartImportJobsJobIdConfirm(c, jobId)
}

// PostCartItems operation middleware
func (siw *ServerInterfaceWrapper) PostCartItems(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCartItems(c)
}

// DeleteCartItemsItemId operation middleware
func (siw *ServerInterfaceWrapper) DeleteCartItemsItemId(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", c.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCartItemsItemId(c, itemId)
}

// PatchCartItemsItemId operation middleware
func (siw *ServerInterfaceWrapper) PatchCartItemsItemId(c *gin.Context) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", c.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter itemId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchCartItemsItemId(c, itemId)
}

// GetCatalogCategories operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogCategories(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogCategories(c)
}

// PostCatalogCategories operation middleware
func (siw *ServerInterfaceWrapper) PostCatalogCategories(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCatalogCategories(c)
}

// DeleteCatalogCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) DeleteCatalogCategoriesCategoryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCatalogCategoriesCategoryId(c, categoryId)
}

// GetCatalogCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogCategoriesCategoryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogCategoriesCategoryId(c, categoryId)
}

// PatchCatalogCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) PatchCatalogCategoriesCategoryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchCatalogCategoriesCategoryId(c, categoryId)
}

// GetCatalogProducts operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogProducts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCatalogProductsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameter("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogProducts(c, params)
}

// PostCatalogProducts operation middleware
func (siw *ServerInterfaceWrapper) PostCatalogProducts(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCatalogProducts(c)
}

// DeleteCatalogProductsSpuId operation middleware
func (siw *ServerInterfaceWrapper) DeleteCatalogProductsSpuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "spuId" -------------
	var spuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spuId", c.Param("spuId"), &spuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spuId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCatalogProductsSpuId(c, spuId)
}

// GetCatalogProductsSpuId operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogProductsSpuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "spuId" -------------
	var spuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spuId", c.Param("spuId"), &spuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spuId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogProductsSpuId(c, spuId)
}

// PatchCatalogProductsSpuId operation middleware
func (siw *ServerInterfaceWrapper) PatchCatalogProductsSpuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "spuId" -------------
	var spuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spuId", c.Param("spuId"), &spuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spuId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchCatalogProductsSpuId(c, spuId)
}

// PostCatalogProductsSpuIdSkus operation middleware
func (siw *ServerInterfaceWrapper) PostCatalogProductsSpuIdSkus(c *gin.Context) {

	var err error

	// ------------- Path parameter "spuId" -------------
	var spuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spuId", c.Param("spuId"), &spuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spuId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCatalogProductsSpuIdSkus(c, spuId)
}

// GetInquiriesPrice operation middleware
func (siw *ServerInterfaceWrapper) GetInquiriesPrice(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInquiriesPriceParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInquiriesPrice(c, params)
}

// PostInquiriesPrice operation middleware
func (siw *ServerInterfaceWrapper) PostInquiriesPrice(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostInquiriesPrice(c)
}

// GetInquiriesPriceInquiryId operation middleware
func (siw *ServerInterfaceWrapper) GetInquiriesPriceInquiryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "inquiryId" -------------
	var inquiryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inquiryId", c.Param("inquiryId"), &inquiryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter inquiryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInquiriesPriceInquiryId(c, inquiryId)
}

// PatchInquiriesPriceInquiryId operation middleware
func (siw *ServerInterfaceWrapper) PatchInquiriesPriceInquiryId(c *gin.Context) {

	var err error

	// ------------- Path parameter "inquiryId" -------------
	var inquiryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inquiryId", c.Param("inquiryId"), &inquiryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter inquiryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchInquiriesPriceInquiryId(c, inquiryId)
}

// GetInquiriesPriceInquiryIdMessages operation middleware
func (siw *ServerInterfaceWrapper) GetInquiriesPriceInquiryIdMessages(c *gin.Context) {

	var err error

	// ------------- Path parameter "inquiryId" -------------
	var inquiryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inquiryId", c.Param("inquiryId"), &inquiryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter inquiryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInquiriesPriceInquiryIdMessagesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInquiriesPriceInquiryIdMessages(c, inquiryId, params)
}

// PostInquiriesPriceInquiryIdMessages operation middleware
func (siw *ServerInterfaceWrapper) PostInquiriesPriceInquiryIdMessages(c *gin.Context) {

	var err error

	// ------------- Path parameter "inquiryId" -------------
	var inquiryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inquiryId", c.Param("inquiryId"), &inquiryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter inquiryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostInquiriesPriceInquiryIdMessages(c, inquiryId)
}

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	// ------------- Optional query parameter "customerId" -------------

	err = runtime.BindQueryParameter("form", true, false, "customerId", c.Request.URL.Query(), &params.CustomerId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ownerSalesUserId" -------------

	err = runtime.BindQueryParameter("form", true, false, "ownerSalesUserId", c.Request.URL.Query(), &params.OwnerSalesUserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ownerSalesUserId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrders(c, params)
}

// PostOrders operation middleware
func (siw *ServerInterfaceWrapper) PostOrders(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostOrdersParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostOrders(c, params)
}

// GetOrdersStats operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersStats(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrdersStats(c)
}

// GetOrdersOrderId operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderId(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", c.Param("orderId"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrdersOrderId(c, orderId)
}

// GetOrdersOrderIdTracking operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderIdTracking(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", c.Param("orderId"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrdersOrderIdTracking(c, orderId)
}

// PostOrdersOrderIdTracking operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdTracking(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", c.Param("orderId"), &orderId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostOrdersOrderIdTracking(c, orderId)
}

// GetProductRequests operation middleware
func (siw *ServerInterfaceWrapper) GetProductRequests(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductRequestsParams

	// ------------- Optional query parameter "createdAfter" -------------

	err = runtime.BindQueryParameter("form", true, false, "createdAfter", c.Request.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter createdAfter: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "createdBefore" -------------

	err = runtime.BindQueryParameter("form", true, false, "createdBefore", c.Request.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter createdBefore: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductRequests(c, params)
}

// PostProductRequests operation middleware
func (siw *ServerInterfaceWrapper) PostProductRequests(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProductRequests(c)
}

// PostProductRequestsAssets operation middleware
func (siw *ServerInterfaceWrapper) PostProductRequestsAssets(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProductRequestsAssets(c)
}

// PostShipmentsImportJobs operation middleware
func (siw *ServerInterfaceWrapper) PostShipmentsImportJobs(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostShipmentsImportJobs(c)
}

// GetWishlist operation middleware
func (siw *ServerInterfaceWrapper) GetWishlist(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWishlist(c)
}

// PostWishlist operation middleware
func (siw *ServerInterfaceWrapper) PostWishlist(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostWishlist(c)
}

// DeleteWishlistSkuId operation middleware
func (siw *ServerInterfaceWrapper) DeleteWishlistSkuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "skuId" -------------
	var skuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "skuId", c.Param("skuId"), &skuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter skuId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteWishlistSkuId(c, skuId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/addresses", wrapper.GetAddresses)
	router.POST(options.BaseURL+"/addresses", wrapper.PostAddresses)
	router.DELETE(options.BaseURL+"/addresses/:addressId", wrapper.DeleteAddressesAddressId)
	router.PATCH(options.BaseURL+"/addresses/:addressId", wrapper.PatchAddressesAddressId)
	router.GET(options.BaseURL+"/after-sales/tickets", wrapper.GetAfterSalesTickets)
	router.POST(options.BaseURL+"/after-sales/tickets", wrapper.PostAfterSalesTickets)
	router.GET(options.BaseURL+"/after-sales/tickets/:ticketId", wrapper.GetAfterSalesTicketsTicketId)
	router.PATCH(options.BaseURL+"/after-sales/tickets/:ticketId", wrapper.PatchAfterSalesTicketsTicketId)
	router.GET(options.BaseURL+"/after-sales/tickets/:ticketId/messages", wrapper.GetAfterSalesTicketsTicketIdMessages)
	router.POST(options.BaseURL+"/after-sales/tickets/:ticketId/messages", wrapper.PostAfterSalesTicketsTicketIdMessages)
	router.GET(options.BaseURL+"/cart", wrapper.GetCart)
	router.POST(options.BaseURL+"/cart/import-jobs", wrapper.PostCartImportJobs)
	router.GET(options.BaseURL+"/cart/import-jobs/:jobId", wrapper.GetCartImportJobsJobId)
	router.POST(options.BaseURL+"/cart/import-jobs/:jobId/confirm", wrapper.PostCartImportJobsJobIdConfirm)
	router.POST(options.BaseURL+"/cart/items", wrapper.PostCartItems)
	router.DELETE(options.BaseURL+"/cart/items/:itemId", wrapper.DeleteCartItemsItemId)
	router.PATCH(options.BaseURL+"/cart/items/:itemId", wrapper.PatchCartItemsItemId)
	router.GET(options.BaseURL+"/catalog/categories", wrapper.GetCatalogCategories)
	router.POST(options.BaseURL+"/catalog/categories", wrapper.PostCatalogCategories)
	router.DELETE(options.BaseURL+"/catalog/categories/:categoryId", wrapper.DeleteCatalogCategoriesCategoryId)
	router.GET(options.BaseURL+"/catalog/categories/:categoryId", wrapper.GetCatalogCategoriesCategoryId)
	router.PATCH(options.BaseURL+"/catalog/categories/:categoryId", wrapper.PatchCatalogCategoriesCategoryId)
	router.GET(options.BaseURL+"/catalog/products", wrapper.GetCatalogProducts)
	router.POST(options.BaseURL+"/catalog/products", wrapper.PostCatalogProducts)
	router.DELETE(options.BaseURL+"/catalog/products/:spuId", wrapper.DeleteCatalogProductsSpuId)
	router.GET(options.BaseURL+"/catalog/products/:spuId", wrapper.GetCatalogProductsSpuId)
	router.PATCH(options.BaseURL+"/catalog/products/:spuId", wrapper.PatchCatalogProductsSpuId)
	router.POST(options.BaseURL+"/catalog/products/:spuId/skus", wrapper.PostCatalogProductsSpuIdSkus)
	router.GET(options.BaseURL+"/inquiries/price", wrapper.GetInquiriesPrice)
	router.POST(options.BaseURL+"/inquiries/price", wrapper.PostInquiriesPrice)
	router.GET(options.BaseURL+"/inquiries/price/:inquiryId", wrapper.GetInquiriesPriceInquiryId)
	router.PATCH(options.BaseURL+"/inquiries/price/:inquiryId", wrapper.PatchInquiriesPriceInquiryId)
	router.GET(options.BaseURL+"/inquiries/price/:inquiryId/messages", wrapper.GetInquiriesPriceInquiryIdMessages)
	router.POST(options.BaseURL+"/inquiries/price/:inquiryId/messages", wrapper.PostInquiriesPriceInquiryIdMessages)
	router.GET(options.BaseURL+"/orders", wrapper.GetOrders)
	router.POST(options.BaseURL+"/orders", wrapper.PostOrders)
	router.GET(options.BaseURL+"/orders/stats", wrapper.GetOrdersStats)
	router.GET(options.BaseURL+"/orders/:orderId", wrapper.GetOrdersOrderId)
	router.GET(options.BaseURL+"/orders/:orderId/tracking", wrapper.GetOrdersOrderIdTracking)
	router.POST(options.BaseURL+"/orders/:orderId/tracking", wrapper.PostOrdersOrderIdTracking)
	router.GET(options.BaseURL+"/product-requests", wrapper.GetProductRequests)
	router.POST(options.BaseURL+"/product-requests", wrapper.PostProductRequests)
	router.POST(options.BaseURL+"/product-requests/assets", wrapper.PostProductRequestsAssets)
	router.POST(options.BaseURL+"/shipments/import-jobs", wrapper.PostShipmentsImportJobs)
	router.GET(options.BaseURL+"/wishlist", wrapper.GetWishlist)
	router.POST(options.BaseURL+"/wishlist", wrapper.PostWishlist)
	router.DELETE(options.BaseURL+"/wishlist/:skuId", wrapper.DeleteWishlistSkuId)
}
