// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Category defines model for Category.
type Category struct {
	Id       openapi_types.UUID  `json:"id"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId"`
	Sort     *int                `json:"sort,omitempty"`
}

// CreateCatalogProductRequest defines model for CreateCatalogProductRequest.
type CreateCatalogProductRequest struct {
	CategoryId       openapi_types.UUID `json:"categoryId"`
	CoverImageUrl    *string            `json:"coverImageUrl,omitempty"`
	Description      *string            `json:"description,omitempty"`
	FilterDimensions *[]string          `json:"filterDimensions,omitempty"`
	Images           *[]string          `json:"images,omitempty"`
	Name             string             `json:"name"`
	Tags             *[]string          `json:"tags,omitempty"`
}

// PagedProductList defines model for PagedProductList.
type PagedProductList struct {
	Items    []ProductSummary `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// PriceTier defines model for PriceTier.
type PriceTier struct {
	// MaxQty null means no upper bound
	MaxQty    *int    `json:"maxQty"`
	MinQty    int     `json:"minQty"`
	UnitPrice float32 `json:"unitPrice"`
}

// ProductDetail defines model for ProductDetail.
type ProductDetail struct {
	Product struct {
		CategoryId  openapi_types.UUID `json:"categoryId"`
		Description *string            `json:"description,omitempty"`

		// FilterDimensions For multi-level filtering, e.g., material -> length -> size
		FilterDimensions *[]string          `json:"filterDimensions,omitempty"`
		Id               openapi_types.UUID `json:"id"`
		Images           *[]string          `json:"images,omitempty"`
		Name             string             `json:"name"`
	} `json:"product"`
	Skus []SKU `json:"skus"`
}

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	CategoryId    openapi_types.UUID `json:"categoryId"`
	CoverImageUrl *string            `json:"coverImageUrl,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
	Tags          *[]string          `json:"tags,omitempty"`
}

// SKU defines model for SKU.
type SKU struct {
	Attributes *map[string]string `json:"attributes,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	IsActive   bool               `json:"isActive"`
	Name       string             `json:"name"`
	PriceTiers *[]PriceTier       `json:"priceTiers,omitempty"`
	SkuCode    *string            `json:"skuCode,omitempty"`
	SpuId      openapi_types.UUID `json:"spuId"`
	Unit       *string            `json:"unit,omitempty"`
}

// GetCatalogProductsParams defines parameters for GetCatalogProducts.
type GetCatalogProductsParams struct {
	Q          *string             `form:"q,omitempty" json:"q,omitempty"`
	CategoryId *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	Page       *int                `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *int                `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostCatalogProductsJSONRequestBody defines body for PostCatalogProducts for application/json ContentType.
type PostCatalogProductsJSONRequestBody = CreateCatalogProductRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List categories
	// (GET /catalog/categories)
	GetCatalogCategories(c *gin.Context)
	// Search/list products (SPU list)
	// (GET /catalog/products)
	GetCatalogProducts(c *gin.Context, params GetCatalogProductsParams)
	// Create product (SPU)
	// (POST /catalog/products)
	PostCatalogProducts(c *gin.Context)
	// Get product detail (SPU + SKU summary)
	// (GET /catalog/products/{spuId})
	GetCatalogProductsSpuId(c *gin.Context, spuId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCatalogCategories operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogCategories(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogCategories(c)
}

// GetCatalogProducts operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogProducts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCatalogProductsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameter("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogProducts(c, params)
}

// PostCatalogProducts operation middleware
func (siw *ServerInterfaceWrapper) PostCatalogProducts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCatalogProducts(c)
}

// GetCatalogProductsSpuId operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogProductsSpuId(c *gin.Context) {

	var err error

	// ------------- Path parameter "spuId" -------------
	var spuId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spuId", c.Param("spuId"), &spuId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spuId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogProductsSpuId(c, spuId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/catalog/categories", wrapper.GetCatalogCategories)
	router.GET(options.BaseURL+"/catalog/products", wrapper.GetCatalogProducts)
	router.POST(options.BaseURL+"/catalog/products", wrapper.PostCatalogProducts)
	router.GET(options.BaseURL+"/catalog/products/:spuId", wrapper.GetCatalogProductsSpuId)
}
