// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/teamdsb/tmo/services/payment/internal/http/oapi/common"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PaymentChannel.
const (
	ALIPAY PaymentChannel = "ALIPAY"
	WECHAT PaymentChannel = "WECHAT"
)

// Defines values for PaymentClientResult.
const (
	PaymentClientResultCANCELLED PaymentClientResult = "CANCELLED"
	PaymentClientResultFAILED    PaymentClientResult = "FAILED"
	PaymentClientResultSUCCESS   PaymentClientResult = "SUCCESS"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCANCELLED  PaymentStatus = "CANCELLED"
	PaymentStatusPAID       PaymentStatus = "PAID"
	PaymentStatusPAYFAILED  PaymentStatus = "PAY_FAILED"
	PaymentStatusPAYPENDING PaymentStatus = "PAY_PENDING"
)

// AlipayPayCreateResponse defines model for AlipayPayCreateResponse.
type AlipayPayCreateResponse struct {
	Channel   PaymentChannel         `json:"channel"`
	ExpiresAt time.Time              `json:"expiresAt"`
	OrderId   openapi_types.UUID     `json:"orderId"`
	PayParams map[string]interface{} `json:"payParams"`
	PaymentId openapi_types.UUID     `json:"paymentId"`
	Status    PaymentStatus          `json:"status"`
	TradeNo   string                 `json:"tradeNo"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = externalRef0.ErrorResponse

// PaymentChannel defines model for PaymentChannel.
type PaymentChannel string

// PaymentClientResult defines model for PaymentClientResult.
type PaymentClientResult string

// PaymentDetail defines model for PaymentDetail.
type PaymentDetail struct {
	AmountFen        int64               `json:"amountFen"`
	Channel          PaymentChannel      `json:"channel"`
	CreatedAt        time.Time           `json:"createdAt"`
	Currency         string              `json:"currency"`
	FailureCode      *string             `json:"failureCode"`
	FailureMessage   *string             `json:"failureMessage"`
	Id               openapi_types.UUID  `json:"id"`
	OrderId          openapi_types.UUID  `json:"orderId"`
	PaidAt           *time.Time          `json:"paidAt"`
	PayerUserId      *openapi_types.UUID `json:"payerUserId"`
	ProviderPrepayId *string             `json:"providerPrepayId"`
	ProviderTradeNo  *string             `json:"providerTradeNo"`
	Status           PaymentStatus       `json:"status"`
	UpdatedAt        time.Time           `json:"updatedAt"`
}

// PaymentRecheckRequest defines model for PaymentRecheckRequest.
type PaymentRecheckRequest struct {
	ClientResult *PaymentClientResult `json:"clientResult,omitempty"`
	Reason       *string              `json:"reason,omitempty"`
}

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// WechatPayCreateResponse defines model for WechatPayCreateResponse.
type WechatPayCreateResponse struct {
	Channel   PaymentChannel     `json:"channel"`
	ExpiresAt time.Time          `json:"expiresAt"`
	NonceStr  string             `json:"nonceStr"`
	OrderId   openapi_types.UUID `json:"orderId"`
	Package   string             `json:"package"`
	PaySign   string             `json:"paySign"`
	PaymentId openapi_types.UUID `json:"paymentId"`
	PrepayId  string             `json:"prepayId"`
	SignType  string             `json:"signType"`
	Status    PaymentStatus      `json:"status"`
	TimeStamp string             `json:"timeStamp"`
}

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PostPaymentsAlipayCreateJSONBody defines parameters for PostPaymentsAlipayCreate.
type PostPaymentsAlipayCreateJSONBody struct {
	OrderId openapi_types.UUID `json:"orderId"`
}

// PostPaymentsAlipayCreateParams defines parameters for PostPaymentsAlipayCreate.
type PostPaymentsAlipayCreateParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// PostPaymentsAlipayNotifyJSONBody defines parameters for PostPaymentsAlipayNotify.
type PostPaymentsAlipayNotifyJSONBody map[string]interface{}

// PostPaymentsWechatCreateJSONBody defines parameters for PostPaymentsWechatCreate.
type PostPaymentsWechatCreateJSONBody struct {
	OrderId openapi_types.UUID `json:"orderId"`
}

// PostPaymentsWechatCreateParams defines parameters for PostPaymentsWechatCreate.
type PostPaymentsWechatCreateParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// PostPaymentsWechatNotifyJSONBody defines parameters for PostPaymentsWechatNotify.
type PostPaymentsWechatNotifyJSONBody map[string]interface{}

// PostPaymentsAlipayCreateJSONRequestBody defines body for PostPaymentsAlipayCreate for application/json ContentType.
type PostPaymentsAlipayCreateJSONRequestBody PostPaymentsAlipayCreateJSONBody

// PostPaymentsAlipayNotifyJSONRequestBody defines body for PostPaymentsAlipayNotify for application/json ContentType.
type PostPaymentsAlipayNotifyJSONRequestBody PostPaymentsAlipayNotifyJSONBody

// PostPaymentsWechatCreateJSONRequestBody defines body for PostPaymentsWechatCreate for application/json ContentType.
type PostPaymentsWechatCreateJSONRequestBody PostPaymentsWechatCreateJSONBody

// PostPaymentsWechatNotifyJSONRequestBody defines body for PostPaymentsWechatNotify for application/json ContentType.
type PostPaymentsWechatNotifyJSONRequestBody PostPaymentsWechatNotifyJSONBody

// PostPaymentsPaymentIdRecheckJSONRequestBody defines body for PostPaymentsPaymentIdRecheck for application/json ContentType.
type PostPaymentsPaymentIdRecheckJSONRequestBody = PaymentRecheckRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create Alipay payment for an order (reserved, behind feature flag)
	// (POST /payments/alipay/create)
	PostPaymentsAlipayCreate(c *gin.Context, params PostPaymentsAlipayCreateParams)
	// Alipay callback (no auth, signature verified)
	// (POST /payments/alipay/notify)
	PostPaymentsAlipayNotify(c *gin.Context)
	// Create WeChat payment for an order (behind feature flag)
	// (POST /payments/wechat/create)
	PostPaymentsWechatCreate(c *gin.Context, params PostPaymentsWechatCreateParams)
	// WeChat pay callback (no auth, signature verified)
	// (POST /payments/wechat/notify)
	PostPaymentsWechatNotify(c *gin.Context)
	// Get payment detail
	// (GET /payments/{paymentId})
	GetPaymentsPaymentId(c *gin.Context, paymentId openapi_types.UUID)
	// Recheck payment result after client pay flow
	// (POST /payments/{paymentId}/recheck)
	PostPaymentsPaymentIdRecheck(c *gin.Context, paymentId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostPaymentsAlipayCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPaymentsAlipayCreate(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostPaymentsAlipayCreateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPaymentsAlipayCreate(c, params)
}

// PostPaymentsAlipayNotify operation middleware
func (siw *ServerInterfaceWrapper) PostPaymentsAlipayNotify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPaymentsAlipayNotify(c)
}

// PostPaymentsWechatCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPaymentsWechatCreate(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostPaymentsWechatCreateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPaymentsWechatCreate(c, params)
}

// PostPaymentsWechatNotify operation middleware
func (siw *ServerInterfaceWrapper) PostPaymentsWechatNotify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPaymentsWechatNotify(c)
}

// GetPaymentsPaymentId operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentsPaymentId(c *gin.Context) {

	var err error

	// ------------- Path parameter "paymentId" -------------
	var paymentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "paymentId", c.Param("paymentId"), &paymentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter paymentId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPaymentsPaymentId(c, paymentId)
}

// PostPaymentsPaymentIdRecheck operation middleware
func (siw *ServerInterfaceWrapper) PostPaymentsPaymentIdRecheck(c *gin.Context) {

	var err error

	// ------------- Path parameter "paymentId" -------------
	var paymentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "paymentId", c.Param("paymentId"), &paymentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter paymentId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPaymentsPaymentIdRecheck(c, paymentId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/payments/alipay/create", wrapper.PostPaymentsAlipayCreate)
	router.POST(options.BaseURL+"/payments/alipay/notify", wrapper.PostPaymentsAlipayNotify)
	router.POST(options.BaseURL+"/payments/wechat/create", wrapper.PostPaymentsWechatCreate)
	router.POST(options.BaseURL+"/payments/wechat/notify", wrapper.PostPaymentsWechatNotify)
	router.GET(options.BaseURL+"/payments/:paymentId", wrapper.GetPaymentsPaymentId)
	router.POST(options.BaseURL+"/payments/:paymentId/recheck", wrapper.PostPaymentsPaymentIdRecheck)
}
