// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SalesQrCode struct {
	Scene       string             `db:"scene" json:"scene"`
	SalesUserID uuid.UUID          `db:"sales_user_id" json:"sales_user_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	DisplayName      *string            `db:"display_name" json:"display_name"`
	UserType         string             `db:"user_type" json:"user_type"`
	OwnerSalesUserID pgtype.UUID        `db:"owner_sales_user_id" json:"owner_sales_user_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserIdentity struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderUserID string             `db:"provider_user_id" json:"provider_user_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserPassword struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
