// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"time"

	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for MiniLoginRequestPlatform.
const (
	Alipay MiniLoginRequestPlatform = "alipay"
	Weapp  MiniLoginRequestPlatform = "weapp"
)

// Defines values for MiniLoginRequestRole.
const (
	CS          MiniLoginRequestRole = "CS"
	CUSTOMER    MiniLoginRequestRole = "CUSTOMER"
	PROCUREMENT MiniLoginRequestRole = "PROCUREMENT"
	SALES       MiniLoginRequestRole = "SALES"
)

// Defines values for PasswordLoginRequestRole.
const (
	ADMIN PasswordLoginRequestRole = "ADMIN"
)

// Defines values for UserUserType.
const (
	Admin    UserUserType = "admin"
	Customer UserUserType = "customer"
	Staff    UserUserType = "staff"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	ExpiresIn   int    `json:"expiresIn"`
	User        User   `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code string `json:"code"`

	// Details Optional metadata (e.g. { "availableRoles": ["CUSTOMER", "SALES"] }).
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId string                  `json:"requestId"`
}

// MiniLoginRequest defines model for MiniLoginRequest.
type MiniLoginRequest struct {
	Code     string                   `json:"code"`
	Platform MiniLoginRequestPlatform `json:"platform"`

	// Role Optional current role; required when multiple roles. ADMIN is not allowed.
	Role *MiniLoginRequestRole `json:"role,omitempty"`

	// Scene Optional: QR scene parameter for sales binding (only applied on first bind)
	Scene *string `json:"scene,omitempty"`
}

// MiniLoginRequestPlatform defines model for MiniLoginRequest.Platform.
type MiniLoginRequestPlatform string

// MiniLoginRequestRole Optional current role; required when multiple roles. ADMIN is not allowed.
type MiniLoginRequestRole string

// PasswordLoginRequest defines model for PasswordLoginRequest.
type PasswordLoginRequest struct {
	Password string `json:"password"`

	// Role Optional; must be ADMIN when provided.
	Role     *PasswordLoginRequestRole `json:"role,omitempty"`
	Username string                    `json:"username"`
}

// PasswordLoginRequestRole Optional; must be ADMIN when provided.
type PasswordLoginRequestRole string

// SalesQrCode defines model for SalesQrCode.
type SalesQrCode struct {
	ExpiresAt *time.Time `json:"expiresAt"`
	QrCodeUrl string     `json:"qrCodeUrl"`

	// Scene Scene parameter used for sales binding
	Scene string `json:"scene"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time          `json:"createdAt"`
	DisplayName *string            `json:"displayName,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Roles       []string           `json:"roles"`
	UserType    UserUserType       `json:"userType"`
}

// UserUserType defines model for User.UserType.
type UserUserType string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PostAuthMiniLoginJSONRequestBody defines body for PostAuthMiniLogin for application/json ContentType.
type PostAuthMiniLoginJSONRequestBody = MiniLoginRequest

// PostAuthPasswordLoginJSONRequestBody defines body for PostAuthPasswordLogin for application/json ContentType.
type PostAuthPasswordLoginJSONRequestBody = PasswordLoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Mini program login (customer/staff, WeChat/Alipay)
	// (POST /auth/mini/login)
	PostAuthMiniLogin(c *gin.Context)
	// Admin web password login
	// (POST /auth/password/login)
	PostAuthPasswordLogin(c *gin.Context)
	// Get current user
	// (GET /me)
	GetMe(c *gin.Context)
	// Get sales binding QR code (sales only)
	// (GET /me/sales-qr-code)
	GetMeSalesQrCode(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthMiniLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMiniLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthMiniLogin(c)
}

// PostAuthPasswordLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthPasswordLogin(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetMeSalesQrCode operation middleware
func (siw *ServerInterfaceWrapper) GetMeSalesQrCode(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMeSalesQrCode(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/mini/login", wrapper.PostAuthMiniLogin)
	router.POST(options.BaseURL+"/auth/password/login", wrapper.PostAuthPasswordLogin)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/me/sales-qr-code", wrapper.GetMeSalesQrCode)
}
