// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	OrderID          uuid.UUID          `db:"order_id" json:"order_id"`
	PayerUserID      pgtype.UUID        `db:"payer_user_id" json:"payer_user_id"`
	Channel          string             `db:"channel" json:"channel"`
	Status           string             `db:"status" json:"status"`
	AmountFen        int64              `db:"amount_fen" json:"amount_fen"`
	Currency         string             `db:"currency" json:"currency"`
	IdempotencyKey   *string            `db:"idempotency_key" json:"idempotency_key"`
	ProviderTradeNo  *string            `db:"provider_trade_no" json:"provider_trade_no"`
	ProviderPrepayID *string            `db:"provider_prepay_id" json:"provider_prepay_id"`
	ProviderPayload  json.RawMessage    `db:"provider_payload" json:"provider_payload"`
	FailureCode      *string            `db:"failure_code" json:"failure_code"`
	FailureMessage   *string            `db:"failure_message" json:"failure_message"`
	PaidAt           pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ClosedAt         pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PaymentAuditLog struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	PaymentID pgtype.UUID        `db:"payment_id" json:"payment_id"`
	Action    string             `db:"action" json:"action"`
	Actor     string             `db:"actor" json:"actor"`
	Detail    string             `db:"detail" json:"detail"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PaymentWebhook struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	PaymentID      pgtype.UUID        `db:"payment_id" json:"payment_id"`
	Provider       string             `db:"provider" json:"provider"`
	EventType      string             `db:"event_type" json:"event_type"`
	DeliveryStatus string             `db:"delivery_status" json:"delivery_status"`
	RawBody        json.RawMessage    `db:"raw_body" json:"raw_body"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	ProcessedAt    pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
