// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPaymentAuditLogs = `-- name: CountPaymentAuditLogs :one
SELECT count(*)
FROM payment_audit_logs
WHERE (
    $1::text IS NULL
    OR detail ILIKE '%' || $1 || '%'
    OR COALESCE(payment_id::text, '') ILIKE '%' || $1 || '%'
)
  AND ($2::text IS NULL OR action = $2)
`

type CountPaymentAuditLogsParams struct {
	Q      *string `db:"q" json:"q"`
	Action *string `db:"action" json:"action"`
}

func (q *Queries) CountPaymentAuditLogs(ctx context.Context, arg CountPaymentAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentAuditLogs, arg.Q, arg.Action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentWebhooks = `-- name: CountPaymentWebhooks :one
SELECT count(*)
FROM payment_webhooks
WHERE (
    $1::text IS NULL
    OR id::text ILIKE '%' || $1 || '%'
    OR event_type ILIKE '%' || $1 || '%'
    OR COALESCE(payment_id::text, '') ILIKE '%' || $1 || '%'
)
  AND ($2::text IS NULL OR provider = $2)
`

type CountPaymentWebhooksParams struct {
	Q        *string `db:"q" json:"q"`
	Provider *string `db:"provider" json:"provider"`
}

func (q *Queries) CountPaymentWebhooks(ctx context.Context, arg CountPaymentWebhooksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentWebhooks, arg.Q, arg.Provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayments = `-- name: CountPayments :one
SELECT count(*)
FROM payments
WHERE (
    $1::text IS NULL
    OR id::text ILIKE '%' || $1 || '%'
    OR order_id::text ILIKE '%' || $1 || '%'
    OR COALESCE(provider_trade_no, '') ILIKE '%' || $1 || '%'
    OR COALESCE(payer_user_id::text, '') ILIKE '%' || $1 || '%'
)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR channel = $3)
`

type CountPaymentsParams struct {
	Q       *string `db:"q" json:"q"`
	Status  *string `db:"status" json:"status"`
	Channel *string `db:"channel" json:"channel"`
}

func (q *Queries) CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, arg.Q, arg.Status, arg.Channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    payer_user_id,
    channel,
    status,
    amount_fen,
    currency,
    idempotency_key,
    provider_trade_no,
    provider_prepay_id,
    provider_payload,
    failure_code,
    failure_message,
    paid_at,
    closed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, order_id, payer_user_id, channel, status, amount_fen, currency, idempotency_key, provider_trade_no, provider_prepay_id, provider_payload, failure_code, failure_message, paid_at, closed_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID          uuid.UUID          `db:"order_id" json:"order_id"`
	PayerUserID      pgtype.UUID        `db:"payer_user_id" json:"payer_user_id"`
	Channel          string             `db:"channel" json:"channel"`
	Status           string             `db:"status" json:"status"`
	AmountFen        int64              `db:"amount_fen" json:"amount_fen"`
	Currency         string             `db:"currency" json:"currency"`
	IdempotencyKey   *string            `db:"idempotency_key" json:"idempotency_key"`
	ProviderTradeNo  *string            `db:"provider_trade_no" json:"provider_trade_no"`
	ProviderPrepayID *string            `db:"provider_prepay_id" json:"provider_prepay_id"`
	ProviderPayload  json.RawMessage    `db:"provider_payload" json:"provider_payload"`
	FailureCode      *string            `db:"failure_code" json:"failure_code"`
	FailureMessage   *string            `db:"failure_message" json:"failure_message"`
	PaidAt           pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ClosedAt         pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.PayerUserID,
		arg.Channel,
		arg.Status,
		arg.AmountFen,
		arg.Currency,
		arg.IdempotencyKey,
		arg.ProviderTradeNo,
		arg.ProviderPrepayID,
		arg.ProviderPayload,
		arg.FailureCode,
		arg.FailureMessage,
		arg.PaidAt,
		arg.ClosedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerUserID,
		&i.Channel,
		&i.Status,
		&i.AmountFen,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderTradeNo,
		&i.ProviderPrepayID,
		&i.ProviderPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.PaidAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentAuditLog = `-- name: CreatePaymentAuditLog :one
INSERT INTO payment_audit_logs (
    payment_id,
    action,
    actor,
    detail
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, payment_id, action, actor, detail, created_at
`

type CreatePaymentAuditLogParams struct {
	PaymentID pgtype.UUID `db:"payment_id" json:"payment_id"`
	Action    string      `db:"action" json:"action"`
	Actor     string      `db:"actor" json:"actor"`
	Detail    string      `db:"detail" json:"detail"`
}

func (q *Queries) CreatePaymentAuditLog(ctx context.Context, arg CreatePaymentAuditLogParams) (PaymentAuditLog, error) {
	row := q.db.QueryRow(ctx, createPaymentAuditLog,
		arg.PaymentID,
		arg.Action,
		arg.Actor,
		arg.Detail,
	)
	var i PaymentAuditLog
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Action,
		&i.Actor,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentWebhook = `-- name: CreatePaymentWebhook :one
INSERT INTO payment_webhooks (
    payment_id,
    provider,
    event_type,
    delivery_status,
    raw_body,
    processed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, payment_id, provider, event_type, delivery_status, raw_body, replay_count, processed_at, created_at, updated_at
`

type CreatePaymentWebhookParams struct {
	PaymentID      pgtype.UUID        `db:"payment_id" json:"payment_id"`
	Provider       string             `db:"provider" json:"provider"`
	EventType      string             `db:"event_type" json:"event_type"`
	DeliveryStatus string             `db:"delivery_status" json:"delivery_status"`
	RawBody        json.RawMessage    `db:"raw_body" json:"raw_body"`
	ProcessedAt    pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

func (q *Queries) CreatePaymentWebhook(ctx context.Context, arg CreatePaymentWebhookParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, createPaymentWebhook,
		arg.PaymentID,
		arg.Provider,
		arg.EventType,
		arg.DeliveryStatus,
		arg.RawBody,
		arg.ProcessedAt,
	)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Provider,
		&i.EventType,
		&i.DeliveryStatus,
		&i.RawBody,
		&i.ReplayCount,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, payer_user_id, channel, status, amount_fen, currency, idempotency_key, provider_trade_no, provider_prepay_id, provider_payload, failure_code, failure_message, paid_at, closed_at, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerUserID,
		&i.Channel,
		&i.Status,
		&i.AmountFen,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderTradeNo,
		&i.ProviderPrepayID,
		&i.ProviderPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.PaidAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, order_id, payer_user_id, channel, status, amount_fen, currency, idempotency_key, provider_trade_no, provider_prepay_id, provider_payload, failure_code, failure_message, paid_at, closed_at, created_at, updated_at
FROM payments
WHERE order_id = $1
  AND channel = $2
  AND idempotency_key = $3
`

type GetPaymentByIdempotencyKeyParams struct {
	OrderID        uuid.UUID `db:"order_id" json:"order_id"`
	Channel        string    `db:"channel" json:"channel"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, arg GetPaymentByIdempotencyKeyParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, arg.OrderID, arg.Channel, arg.IdempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerUserID,
		&i.Channel,
		&i.Status,
		&i.AmountFen,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderTradeNo,
		&i.ProviderPrepayID,
		&i.ProviderPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.PaidAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentWebhook = `-- name: GetPaymentWebhook :one
SELECT id, payment_id, provider, event_type, delivery_status, raw_body, replay_count, processed_at, created_at, updated_at
FROM payment_webhooks
WHERE id = $1
`

func (q *Queries) GetPaymentWebhook(ctx context.Context, id uuid.UUID) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, getPaymentWebhook, id)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Provider,
		&i.EventType,
		&i.DeliveryStatus,
		&i.RawBody,
		&i.ReplayCount,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentAuditLogs = `-- name: ListPaymentAuditLogs :many
SELECT id, payment_id, action, actor, detail, created_at
FROM payment_audit_logs
WHERE (
    $1::text IS NULL
    OR detail ILIKE '%' || $1 || '%'
    OR COALESCE(payment_id::text, '') ILIKE '%' || $1 || '%'
)
  AND ($2::text IS NULL OR action = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPaymentAuditLogsParams struct {
	Q      *string `db:"q" json:"q"`
	Action *string `db:"action" json:"action"`
	Offset int32   `db:"offset" json:"offset"`
	Limit  int32   `db:"limit" json:"limit"`
}

func (q *Queries) ListPaymentAuditLogs(ctx context.Context, arg ListPaymentAuditLogsParams) ([]PaymentAuditLog, error) {
	rows, err := q.db.Query(ctx, listPaymentAuditLogs,
		arg.Q,
		arg.Action,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAuditLog
	for rows.Next() {
		var i PaymentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentWebhooks = `-- name: ListPaymentWebhooks :many
SELECT id, payment_id, provider, event_type, delivery_status, raw_body, replay_count, processed_at, created_at, updated_at
FROM payment_webhooks
WHERE (
    $1::text IS NULL
    OR id::text ILIKE '%' || $1 || '%'
    OR event_type ILIKE '%' || $1 || '%'
    OR COALESCE(payment_id::text, '') ILIKE '%' || $1 || '%'
)
  AND ($2::text IS NULL OR provider = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPaymentWebhooksParams struct {
	Q        *string `db:"q" json:"q"`
	Provider *string `db:"provider" json:"provider"`
	Offset   int32   `db:"offset" json:"offset"`
	Limit    int32   `db:"limit" json:"limit"`
}

func (q *Queries) ListPaymentWebhooks(ctx context.Context, arg ListPaymentWebhooksParams) ([]PaymentWebhook, error) {
	rows, err := q.db.Query(ctx, listPaymentWebhooks,
		arg.Q,
		arg.Provider,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentWebhook
	for rows.Next() {
		var i PaymentWebhook
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.Provider,
			&i.EventType,
			&i.DeliveryStatus,
			&i.RawBody,
			&i.ReplayCount,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, payer_user_id, channel, status, amount_fen, currency, idempotency_key, provider_trade_no, provider_prepay_id, provider_payload, failure_code, failure_message, paid_at, closed_at, created_at, updated_at
FROM payments
WHERE (
    $1::text IS NULL
    OR id::text ILIKE '%' || $1 || '%'
    OR order_id::text ILIKE '%' || $1 || '%'
    OR COALESCE(provider_trade_no, '') ILIKE '%' || $1 || '%'
    OR COALESCE(payer_user_id::text, '') ILIKE '%' || $1 || '%'
)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR channel = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListPaymentsParams struct {
	Q       *string `db:"q" json:"q"`
	Status  *string `db:"status" json:"status"`
	Channel *string `db:"channel" json:"channel"`
	Offset  int32   `db:"offset" json:"offset"`
	Limit   int32   `db:"limit" json:"limit"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.Q,
		arg.Status,
		arg.Channel,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PayerUserID,
			&i.Channel,
			&i.Status,
			&i.AmountFen,
			&i.Currency,
			&i.IdempotencyKey,
			&i.ProviderTradeNo,
			&i.ProviderPrepayID,
			&i.ProviderPayload,
			&i.FailureCode,
			&i.FailureMessage,
			&i.PaidAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replayPaymentWebhook = `-- name: ReplayPaymentWebhook :one
UPDATE payment_webhooks
SET replay_count = replay_count + 1,
    delivery_status = $2,
    processed_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, payment_id, provider, event_type, delivery_status, raw_body, replay_count, processed_at, created_at, updated_at
`

type ReplayPaymentWebhookParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	DeliveryStatus string             `db:"delivery_status" json:"delivery_status"`
	ProcessedAt    pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

func (q *Queries) ReplayPaymentWebhook(ctx context.Context, arg ReplayPaymentWebhookParams) (PaymentWebhook, error) {
	row := q.db.QueryRow(ctx, replayPaymentWebhook, arg.ID, arg.DeliveryStatus, arg.ProcessedAt)
	var i PaymentWebhook
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Provider,
		&i.EventType,
		&i.DeliveryStatus,
		&i.RawBody,
		&i.ReplayCount,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentState = `-- name: UpdatePaymentState :one
UPDATE payments
SET status = $2,
    provider_trade_no = COALESCE($3, provider_trade_no),
    provider_prepay_id = COALESCE($4, provider_prepay_id),
    provider_payload = COALESCE($5, provider_payload),
    failure_code = $6,
    failure_message = $7,
    paid_at = $8,
    closed_at = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, order_id, payer_user_id, channel, status, amount_fen, currency, idempotency_key, provider_trade_no, provider_prepay_id, provider_payload, failure_code, failure_message, paid_at, closed_at, created_at, updated_at
`

type UpdatePaymentStateParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Status           string             `db:"status" json:"status"`
	ProviderTradeNo  *string            `db:"provider_trade_no" json:"provider_trade_no"`
	ProviderPrepayID *string            `db:"provider_prepay_id" json:"provider_prepay_id"`
	ProviderPayload  json.RawMessage    `db:"provider_payload" json:"provider_payload"`
	FailureCode      *string            `db:"failure_code" json:"failure_code"`
	FailureMessage   *string            `db:"failure_message" json:"failure_message"`
	PaidAt           pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ClosedAt         pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
}

func (q *Queries) UpdatePaymentState(ctx context.Context, arg UpdatePaymentStateParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentState,
		arg.ID,
		arg.Status,
		arg.ProviderTradeNo,
		arg.ProviderPrepayID,
		arg.ProviderPayload,
		arg.FailureCode,
		arg.FailureMessage,
		arg.PaidAt,
		arg.ClosedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerUserID,
		&i.Channel,
		&i.Status,
		&i.AmountFen,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderTradeNo,
		&i.ProviderPrepayID,
		&i.ProviderPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.PaidAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
