// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimPaymentReconciliation = `-- name: ClaimPaymentReconciliation :one
WITH candidate AS (
    SELECT p.id
    FROM payments p
    WHERE (p.state_version > p.commerce_synced_version
        OR (p.channel = 'WECHAT_B2B' AND p.status = 'PAY_PENDING'))
      AND ($3::boolean OR p.state_version > p.commerce_synced_version)
      AND p.reconcile_after <= now()
      AND (p.reconcile_lease_until IS NULL OR p.reconcile_lease_until <= now())
    ORDER BY p.reconcile_after, p.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE payments p
SET reconcile_lease_token = $1::uuid,
    reconcile_lease_until = now() + $2::bigint * interval '1 millisecond'
FROM candidate
WHERE p.id = candidate.id
RETURNING p.id, p.order_id, p.payer_user_id, p.channel, p.status, p.amount_fen, p.currency, p.idempotency_key, p.provider_trade_no, p.provider_prepay_id, p.provider_payload, p.failure_code, p.failure_message, p.paid_at, p.closed_at, p.created_at, p.updated_at, p.state_version, p.commerce_synced_version, p.reconcile_after, p.reconcile_attempts, p.reconcile_lease_token, p.reconcile_lease_until, p.reconcile_last_error
`

type ClaimPaymentReconciliationParams struct {
	LeaseToken      uuid.UUID `db:"lease_token" json:"lease_token"`
	LeaseDurationMs int64     `db:"lease_duration_ms" json:"lease_duration_ms"`
	QueryB2b        bool      `db:"query_b2b" json:"query_b2b"`
}

func (q *Queries) ClaimPaymentReconciliation(ctx context.Context, arg ClaimPaymentReconciliationParams) (Payment, error) {
	row := q.db.QueryRow(ctx, claimPaymentReconciliation, arg.LeaseToken, arg.LeaseDurationMs, arg.QueryB2b)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PayerUserID,
		&i.Channel,
		&i.Status,
		&i.AmountFen,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderTradeNo,
		&i.ProviderPrepayID,
		&i.ProviderPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.PaidAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateVersion,
		&i.CommerceSyncedVersion,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ReconcileLeaseToken,
		&i.ReconcileLeaseUntil,
		&i.ReconcileLastError,
	)
	return i, err
}

const finishPaymentReconciliation = `-- name: FinishPaymentReconciliation :execrows
UPDATE payments
SET reconcile_after = CASE WHEN state_version <> $1::bigint
        THEN now() ELSE now() + $2::bigint * interval '1 millisecond' END,
    reconcile_attempts = CASE WHEN state_version <> $1::bigint
        THEN 0 ELSE $3::integer END,
    reconcile_last_error = CASE WHEN state_version <> $1::bigint
        THEN NULL ELSE $4::text END,
    reconcile_lease_token = NULL,
    reconcile_lease_until = NULL
WHERE id = $5
  AND reconcile_lease_token = $6::uuid
`

type FinishPaymentReconciliationParams struct {
	ObservedVersion int64     `db:"observed_version" json:"observed_version"`
	RetryAfterMs    int64     `db:"retry_after_ms" json:"retry_after_ms"`
	Attempts        int32     `db:"attempts" json:"attempts"`
	LastError       *string   `db:"last_error" json:"last_error"`
	ID              uuid.UUID `db:"id" json:"id"`
	LeaseToken      uuid.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) FinishPaymentReconciliation(ctx context.Context, arg FinishPaymentReconciliationParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishPaymentReconciliation,
		arg.ObservedVersion,
		arg.RetryAfterMs,
		arg.Attempts,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPaymentCommerceSynced = `-- name: MarkPaymentCommerceSynced :exec
UPDATE payments
SET commerce_synced_version = greatest(commerce_synced_version, $1::bigint)
WHERE id = $2
  AND state_version >= $1::bigint
`

type MarkPaymentCommerceSyncedParams struct {
	SentVersion int64     `db:"sent_version" json:"sent_version"`
	ID          uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkPaymentCommerceSynced(ctx context.Context, arg MarkPaymentCommerceSyncedParams) error {
	_, err := q.db.Exec(ctx, markPaymentCommerceSynced, arg.SentVersion, arg.ID)
	return err
}
