// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"time"

	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/teamdsb/tmo/services/ai/internal/http/oapi/common"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AIReplySuggestionRequest defines model for AIReplySuggestionRequest.
type AIReplySuggestionRequest struct {
	LatestMessageId *openapi_types.UUID `json:"latestMessageId"`
	TicketId        openapi_types.UUID  `json:"ticketId"`
}

// AIReplySuggestions defines model for AIReplySuggestions.
type AIReplySuggestions struct {
	GeneratedAt time.Time          `json:"generatedAt"`
	Suggestions []string           `json:"suggestions"`
	TicketId    openapi_types.UUID `json:"ticketId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = externalRef0.ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PostAiAfterSalesSuggestionsJSONRequestBody defines body for PostAiAfterSalesSuggestions for application/json ContentType.
type PostAiAfterSalesSuggestionsJSONRequestBody = AIReplySuggestionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get AI suggested replies for after-sales
	// (POST /ai/after-sales/suggestions)
	PostAiAfterSalesSuggestions(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAiAfterSalesSuggestions operation middleware
func (siw *ServerInterfaceWrapper) PostAiAfterSalesSuggestions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAiAfterSalesSuggestions(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/ai/after-sales/suggestions", wrapper.PostAiAfterSalesSuggestions)
}
